### ISSUE TITLE
connection.alive() : Database is not callable

### ISSUE THREAD

**Issue by pacud** [mongomock/mongomock#114]
Connection objects in pymongo have an alive method returning True or False depending on the connection to the server. Like : http://nullege.com/codes/search/pymongo.Connection.alive

As it's missing in mongomock the error returned when calling it is : 
TypeError: 'Database' object is not callable

called like this :
dummy_connection = mongomock.MongoClient()
dummy_connection.alive()

**Comment by srinivasreddy** [comment]
This was implemented already. so closing.
