### ISSUE TITLE
Add MongoClientReplicaSet to `mongomock.connection`

### ISSUE THREAD

**Issue by akellehe** [mongomock/mongomock#132]
The behavior should be exactly the same as MongoClient, with the understanding that replication is not actually supported.

``` python
class MongoClientReplicaSet(Connection):
    def stub(self):
        pass
```

**Comment by pcorpet** [comment]
After `pymongo` v3, the `MongoClientReplicaSet` has been merged with `MongoClient` so I think we don't need to do that. Please reopen if I'm mistaken (sorry for the loooooooong delay in the answer).
