### ISSUE TITLE
Can't find a document by string ID

### ISSUE THREAD

**Issue by KimiNewt** [mongomock/mongomock#139]
In normal pymongo, you can look up documents by id using a string (i.e. collection.find({'_id': 'idstring'}). That doesn't work on any mongomock queries, instead requiring an ObjectId object.

**Comment by pcorpet** [comment]
Note that in MongoDb, a `string` and an `ObjectId` with the same value are not the same bson object and as such represent two distinct IDs.

I've just checked with `pymongo` v3.7.1 and a recent MongoDB server and the looking by document ID string did not return any result:

```py
>>> db.a.insert_one({'a': 1}).inserted_id
ObjectId('5b8864c8411f3a000f970df5')
>>> db.a.find_one('5b8864c8411f3a000f970df5')
>>>
>>> list(db.a.find({'_id': '5b8864c8411f3a000f970df5'}))
[]
>>> db.a.find_one(ObjectId('5b8864c8411f3a000f970df5'))
{'_id': ObjectId('5b8864c8411f3a000f970df5'), 'a': 1}
>>> list(db.a.find({'_id': ObjectId('5b8864c8411f3a000f970df5')}))
[{'_id': ObjectId('5b8864c8411f3a000f970df5'), 'a': 1}]
```

Feel free to reopen if I got it wrong somewhere.
