### ISSUE TITLE
mongomock uses random.random(), losing a seed value

### ISSUE THREAD

**Issue by davidwebber** [mongomock/mongomock#147]
Hi All,

Great package!  I have a nitpicky corner case.  Feel free to close this issue if it's not actually a problem.

If I understand correctly, mongomock generates random numbers from the global random.Random instance.  Some users may with to preserve the state of the random number generator (if they're doing Monte-Carlo simulation, for example).  mongomock could instantiate a local instance to preserve the global random generator's state.  Maybe inserting a single line

```
random = random.Random()
```

would be sufficient.

Thanks!

Test code:

``` python
#!/usr/bin/env python

import random
import mongomock
import pymongo

client1 = pymongo.MongoClient("localhost",tz_aware=True)
client2 = mongomock.MongoClient("localhost",tz_aware=True)

local_random = random.Random()

def gen_print_post_random(client, private_random=False):
    if private_random:
        myrandom = local_random
    else:
        myrandom = random
    collection = client["test"]["random_collection"]
    myrandom.seed(1)
    for a in xrange(5):
        value = myrandom.random()
        key = str(a)
        doc = {key:value}
        collection.insert(doc)
        print doc[key]

if __name__=="__main__":
    print "I expected the following trials to have the same result"
    print "real client:"
    gen_print_post_random(client1,False)
    print "mock client:"
    gen_print_post_random(client2,False)

    print "Using a local random instance"
    print "real client:"
    gen_print_post_random(client1,True)
    print "mock client:"
    gen_print_post_random(client2,True)
```

output:

<pre>
I expected the following trials to have the same result
real client:
0.134364244112
0.763774618977
0.495435087092
0.651592972723
0.0938595867742
mock client:
0.134364244112
0.847433736937
0.763774618977
0.255069025739
0.495435087092
Using a local random instance
real client:
0.134364244112
0.847433736937
0.763774618977
0.255069025739
0.495435087092
mock client:
0.134364244112
0.847433736937
0.763774618977
0.255069025739
0.495435087092
</pre>

**Comment by vmalloc** [comment]
Feel free to format a PR and I'll gladly merge it.

**Comment by mdomke** [comment]
I actually don't see were mongomock uses the random library at all (besides in one unittest).

**Comment by pcorpet** [comment]
True we don't use random (at least not yet, as #430 wants to introduce it. I'll make sure we use a local random numbers generator there).
