### ISSUE TITLE
$max update operator support

### ISSUE THREAD

**Issue by borisdan** [mongomock/mongomock#191]
Currently, mongomock doesn't support the $max  update operator. It is not taken into account in _update.

**Comment by deniseirvin** [comment]
Yes I wish $max was implemented too.

**Comment by pcorpet** [comment]
Documentation is here if someone wants to tackle it:
https://docs.mongodb.com/manual/reference/operator/update/max/

**Comment by pcorpet** [comment]
I started adding a unit test but couldn't make it fail: it was implemented in e0de68a6 by @plocharz-9livesdata, thanks Krzysztof.
