### ISSUE TITLE
No 'hint' method for Cursor class

### ISSUE THREAD

**Issue by ymost** [mongomock/mongomock#205]
The cursor class has no `hint` method.
Though hinting is not important when using mongomock, this is a problem when trying to use mongomock as a drop-in replacement for pymongo.

http://api.mongodb.org/python/current/api/pymongo/cursor.html#pymongo.cursor.Cursor.hint

**Comment by pcorpet** [comment]
Hi Yonatan, thanks for reporting and sorry for the delayed answer.

Would you mind taking a look at #485 please?
