### ISSUE TITLE
Add support for initialize_ordered_bulk_op

### ISSUE THREAD

**Issue by moonso** [mongomock/mongomock#210]
Hi, thanks for a nice package!

I get this error when trying to do bulk upserts using initialize_ordered_bulk_op:

```
E       TypeError: 'Collection' object is not callable
```

Same test works if i use regular pymongo MongoClient...

**Comment by okarpovacanopy** [comment]
+1 for this. 
Same for `collection.bulk_write`

**Comment by srinivasreddy** [comment]
@moonso  @okarpovacanopy  will look into that.

**Comment by pcorpet** [comment]
This was implemented by @ddzialak in #178, it should have been available at the time you filed the bug. @moonso please reopen if it's still not working for you, and maybe mention your code that is failing.
