### ISSUE TITLE
Mongomock doesn't drop database depending on connect() arguments

### ISSUE THREAD

**Issue by corydodt** [mongomock/mongomock#233]
For some reason, mongomock doesn't drop the database unless I call connect() and include a `db=` argument in the connection. Easiest way to demonstrate is with two nearly-identical programs:

The first one prints 0, 1, 0. (This is count of Thing at each step.) This is the corrrect output; there should be zero Things at the end.

``` #!python
from mongoengine import connect, Document
c1 = connect(db='asdfasdf', host='mongomock://localhost/asdfasdf')
print 'default ==', c1.get_default_database()
class Thing(Document):
    pass

print 'Thing count ==', Thing.objects.count()
Thing().save()
print 'After save, Thing count ==', Thing.objects.count()
c1.drop_database('asdfasdf')
print 'After drop, Thing count ==', Thing.objects.count()
```

The second one prints 0, 1, 1. This means that the mock database remains, and still contains its Thing, after being dropped.

``` #!python
from mongoengine import connect, Document
c1 = connect(host='mongomock://localhost/asdfasdf')
print 'default ==', c1.get_default_database()
class Thing(Document):
    pass

print 'Thing count ==', Thing.objects.count()
Thing().save()
print 'After save, Thing count ==', Thing.objects.count()
c1.drop_database('asdfasdf')
print 'After drop, Thing count ==', Thing.objects.count()
```

The only difference needed to produce this behavior is to omit the `db=` argument to connect().

The actual mongodb driver does not do this. If I substitute `mongodb://`, both programs produce the output 0, 1, 0.

**Comment by corydodt** [comment]
A bit more info here. Digging in, I found that in the second case, it's saving to the database 'test' in mongomock. Mongomock must be improperly parsing the connect() arguments somehow, since mongodb:// doesn't do the same thing.

**Comment by corydodt** [comment]
(Additionally, there's an obvious workaround for anyone else encountering this: pass in `db=`.)

**Comment by marcioribeirop** [comment]
Thumbs up for the author for opening this Issue. Was struggling with this bug, luckily, the suggested workaround did the tricky. It's a shame that the Mongomock project is sort of abandoned by now, it's actually quite a useful tool.

**Comment by pcorpet** [comment]
Fixed.
