### ISSUE TITLE
mongomock is improperly deleting the database and collections objects when "drop_database" is called

### ISSUE THREAD

**Issue by ericchapman** [mongomock/mongomock#238]
When using mongoengine, during object initialization the "_collections" attribute gets the collections from the database object.  The problem is that mongomock is deleting the collections and database object when "drop_database" is called, therefore making the objects in mongoengine stale.

The fix for this is to

**mongo_client.py**
- Remove line 71 "del self._databases[database_name]"
- Remove line 77 "del self._databases[name_or_db]"

**database.py**
- Remove line 51 "del self._collections[name]"
- Remove line 58 "del self._collections[name_or_collection]"

I checked the behavior when using mongodb and when "drop_database" is called, the DB is sent a "drop database" command but the objects remain since they are considered an abstracted handle to the DB itself.  I believe mongomock should behave the same and simply remove the documents but keep the handles.

Otherwise mongomock is going to somehow have to communicate back up to the mongoengine layer to have it clear out the old handles and get new ones.  I tried having mongoengine refetch the handles from the client on every access but that got really messy.

**Comment by ericchapman** [comment]
Created PR https://github.com/vmalloc/mongomock/pull/245

**Comment by Folyd** [comment]
Does this PR merged to master branch? because the drop_database() bug still alive.
Here are the bug issue. https://github.com/mongomock/mongomock/issues/281

**Comment by ericchapman** [comment]
@Folyd I put this in my requirements.txt to pick up the hacked fix.  Not sure what has changed though since this ticket it was opened.

```
git+https://github.com/ericchapman/mongomock.git@drop_database_fix
```

You could "fork" the repo and create a branch an merge my fix into it and then update the above line to point to your version.  That would give you master and the fix.

**Comment by pcorpet** [comment]
Fixed.
