### ISSUE TITLE
Incorrect aggregate 'func' conditional

### ISSUE THREAD

**Issue by derek-miller** [mongomock/mongomock#242]
In the [`aggregate()`](https://github.com/vmalloc/mongomock/blob/develop/mongomock/collection.py#L1302) mock following conditional exists: [`if func == "$sum" or "$avg":`](https://github.com/vmalloc/mongomock/blob/develop/mongomock/collection.py#L1386). This will result in always evaluating to `True`. It should be `if func == "$sum" or func == "$avg"):`

**Comment by mdomke** [comment]
Or even `if func in {'$sum', '$avg'}`. Feel free to issue a pull-request!

**Comment by srinivasreddy** [comment]
Fixed in https://github.com/mongomock/mongomock/pull/249/
