### ISSUE TITLE
Add support for $slice modifier in $push update operations

### ISSUE THREAD

**Issue by moonso** [mongomock/mongomock#257]
Hi,

I've noticed that the `$slice` operator does not work with mongomock.
If same test if run with a real mongo database this is not a problem.
I can provide with code if necessary...

**Comment by srinivasreddy** [comment]
@moonso We really appreciate you if you can submit a PR.

**Comment by pcorpet** [comment]
@moonso Were you after the [projection operator](https://docs.mongodb.com/manual/reference/operator/projection/slice/), the [aggregation operator](https://docs.mongodb.com/manual/reference/operator/aggregation/slice/), or the [$update parameter](https://docs.mongodb.com/manual/reference/operator/update/slice/)?

We try not to implement all the features, but only those that are requested (and easy to implement).

**Comment by moonso** [comment]
Hi @pcorpet , thank you for continue development! It was the $update parameter that I'm after in this case.

**Comment by boxmansf** [comment]
Any chance to add support for $slice? That would really help one of our usecases! Thanks in advance !

**Comment by pcorpet** [comment]
@boxmansf @moonso I've sent a PR, please review it before I can put it in.

**Comment by boxmansf** [comment]
@pcorpet LGTM
