### ISSUE TITLE
Need to explain how to inject mock into application

### ISSUE THREAD

**Issue by quantoid** [mongomock/mongomock#263]
When testing a Flask or Django application that uses MongoDB by using a test client, it would be useful to be able to replace the normal database object with the mongomock client. How do we do that? Something in the README would be handy.

**Comment by KoleS46** [comment]
@quantoid http://docs.mongoengine.org/guide/mongomock.html

**Comment by quantoid** [comment]
Yes but how do you switch between normal URI for production and mongomock URI for testing? You'd have to select different settings for your app, which is easy for Django but not sure for Flask.

**Comment by texuf** [comment]
save this in a file called db.py, then you'll be able to just use db.foo() 

*also, haven't run this in long time... so someone might want to double check it

    #db.py
    
    """usage
    from db import db
    db.foo()
    """
    
    import os

    ## Environment
    environment = os.environ.get('ENVIRONMENT')

    ## Database
    global mongo

    if environment == 'test':
        global mongo
        import mongomock as mongo
    else:
        global mongo
        import pymongo as mongo

    db_uri = os.environ.get('MONGO_URI', 'mongodb://localhost')
    db_name = os.environ.get('MONGO_DB', 'mydbname')
    db = mongo.MongoClient(db_uri)[db_name]

**Comment by quantoid** [comment]
Ok I think my problems are specific to flask-mongoengine.
