### ISSUE TITLE
Add support for `Cursor.rewind()`

### ISSUE THREAD

**Issue by gmacon** [mongomock/mongomock#268]
It'd be nice for the `Cursor.rewind` method to be handled by mongomock.  I noticed that it was missing when testing some code that makes use of `QuerySet.no_cache()` from MongoEngine. I hope to implement this when I get an hour to spare, but I wanted to go ahead and document this gap now.

**Comment by afouchet** [comment]
Hi,

I'm new to mongomock, but I encounter the following error : 
" AttributeError: 'Cursor' object has no attribute 'rewind' "
Using mongomock 3.7.0

In what release will this feature be used ? 
Are there any work-around until then ?

**Comment by mdomke** [comment]
This is included in release 3.8.0. Sorry for the long waiting time.
