### ISSUE TITLE
mongomock create_index() does not work with sparse=True

### ISSUE THREAD

**Issue by DhirajS** [mongomock/mongomock#275]
The create_index() method in collection.py does not work with the sparse=True option. It is not possible to create an index in mongomock with both unique=True and sparse=True, where some documents are missing the indexed field. The only test coverage for the sparse=True condition is,
```
./tests/test__bulk_operations.py:                _i, unique=False, name="idx" + _i, sparse=True, background=True)
```
and this does not test the unique=True sub-condition.

**Comment by pcorpet** [comment]
This was fixed as part of #316.
