### ISSUE TITLE
MongoClient drop_database() method didn't delete mongoengine Document  _collection property bug!

### ISSUE THREAD

**Issue by Folyd** [mongomock/mongomock#281]
Hi, i were using mongomock as the pytest database, i used such a fixture to setup and teardown database.

    @pytest.yield_fixture(scope='function')
    def database(app):
        with app.app_context():
            db.create_connection()
    
        connection = db.connection
        yield db
        connection.drop_database('test')
        connection.close()

but the  `drop_database()` method  didn't delete mongoengine Document  `_collection` property!
here is the source code:

    @classmethod
    def _get_collection(cls):
        """Returns the collection for the document."""
        # TODO: use new get_collection() with PyMongo3 ?
        if not hasattr(cls, '_collection') or cls._collection is None:
            db = cls._get_db()
            collection_name = cls._get_collection_name()
            # Create collection as a capped collection if specified
            ......
        return cls._collection

However the `_collection` property didn't free up,so the if condition always `True`,  hence the `get_db()` method never got call again!

    def get_db(alias=DEFAULT_CONNECTION_NAME, reconnect=False):
        global _dbs
        if reconnect:
            disconnect(alias)

        if alias not in _dbs:
            conn = get_connection(alias)
            conn_settings = _connection_settings[alias]
            db = conn[conn_settings['name']]
            # Authenticate if necessary
            if conn_settings['username'] and conn_settings['password']:
                db.authenticate(conn_settings['username'],
                                conn_settings['password'],
                                source=conn_settings['authentication_source'])
            _dbs[alias] = db
        return _dbs[alias]

Please fix this bug, thanks very much :)

**Comment by idlesign** [comment]
Dropping collections manually as a finalizer should do the trick for now:

```
    for collection in get_db('mydb')._collections.values():
        collection.drop()
```

**Comment by mdomke** [comment]
Could [pytest-mongodb](https://github.com/mdomke/pytest-mongodb) be of any help for you?

**Comment by idlesign** [comment]
Approach taken in #238 #245 using ``del`` removal should rather be changed into proper collections iteration, since what we really have is ``RuntimeError: dictionary changed size during iteration`` silenced by ``exception pass``.

**Comment by pcorpet** [comment]
Fixed.
