### ISSUE TITLE
collection.database should be a Database, not a Collection

### ISSUE THREAD

**Issue by alanbriolat** [mongomock/mongomock#283]
In writing some tests for a database migration layer that interacts with MongoEngine, I've found that the `database` attribute on mongomock's `Collection` follows the "sub-collection" behaviour rather than exposing the Database object. It seems like what I really want is stored as the `_database` attribute on mongomock's `Collection`.

Expected behaviour is documented [here](http://api.mongodb.com/python/current/api/pymongo/collection.html#pymongo.collection.Collection.database).

**Comment by pcorpet** [comment]
I ran in the same issue and suggested #304

**Comment by pcorpet** [comment]
#304 was merged and fixes this.
