### ISSUE TITLE
Can not handle options for $regex

### ISSUE THREAD

**Issue by moonso** [mongomock/mongomock#306]
Hi and tanks for a nice package.

There are some options available for the regex operator, more described [here](https://docs.mongodb.com/manual/reference/operator/query/regex/).
If you have time ot would be nice to have at least option `'i'` for case insensitive at hand in mongomock.

I've tried to look at the code to fix this myself but can not figure out how to.

Måns

**Comment by DeoLeung** [comment]
@moonso will be good to provide your failing sample code.

but I think you can try `re.compile(..., re.IGNORECASE)`

**Comment by moonso** [comment]
Hi @DeoLeung , there is no exception raised by mongomock but I can tell that it will just ignore the options since if I run the test with a real mongodb as backend the regex search works.

The problem is that I test application code so there is no way I can send in a compiled regular expression. The function takes a string and in the application code, which is an adapter to mongodb, it uses pymongo to do a regex search.

Not sure if providing code would help here...

**Comment by DeoLeung** [comment]
@moonso sample code will definitely help so I can use it to find the problem and verify the mock, e.g #313 

as I never use pure string regex in pymongo before...

**Comment by NazarTopolsky** [comment]
I think I managed to replicate the problem. It seems like pymongo allows using regex in queries in two ways: compiled and plain text. Compiled regular expressions seem to work for me, but plain text versions fail.

I have tested both options on pymongo with a database, and both work as expected. On mongomock, the second (`re_plain_text`) fails.

```python
import re
import mongomock


def re_compiled():
    """Works as expected"""
    docs = [
        {'_id': 1, 'text': 'should appear in Search'},
        {'_id': 2, 'text': 'should not'},
    ]
    query = {
        'text': {'$regex': re.compile('search$', re.IGNORECASE)},
    }
    client = mongomock.MongoClient()
    collection = client.test.regex_test
    collection.insert_many(docs)
    results = list(collection.find(query))
    assert results == [docs[0]]


def re_plain_text():
    """Fails on mongomock"""
    docs = [
        {'_id': 1, 'text': 'should appear in Search'},
        {'_id': 2, 'text': 'should not'},
    ]
    query = {
        'text': {'$regex': 'search$', '$options': 'i'},
    }
    client = mongomock.MongoClient()
    collection = client.test.regex_test
    collection.insert_many(docs)
    results = list(collection.find(query))
    assert results == [docs[0]]


if __name__ == '__main__':
    re_compiled()
    re_plain_text()
```

Also, I disagree with the label "enhancement" since it contradicts the stated goal of mongomock.

>Since this library is used to validate production code, it is unacceptable to behave differently than the real pymongo implementation. In such cases it is better to throw NotImplementedError than implement a modified version of the original behavior.

**Comment by pcorpet** [comment]
Hi @NazarTopolsky , thanks for the long explanation. `mongomock` should raise a `NotImplementedError` in that case indeed. If it does not then it's a bug! However adding the actual feature is an enhancement. So for this one it's both.

**Comment by pcorpet** [comment]
I've fixed the "bug" part, it will now raises a `NotImplementedError`. I'll see if I can implement the actual feature soonish.

**Comment by NazarTopolsky** [comment]
Hi @pcorpet , thanks for the fix.

**Comment by pcorpet** [comment]
@NazarTopolsky can you review #480 please?

**Comment by NazarTopolsky** [comment]
@pcorpet I think the PR looks nice, I don't see any problems with it.
