### ISSUE TITLE
Issue new release

### ISSUE THREAD

**Issue by rcscott** [mongomock/mongomock#308]
Could one one of the project maintainers please issue a new release? I'm specifically hoping to start using #277 since it's been merged. Thanks!

**Comment by srinivasreddy** [comment]
@mdomke  Shall we cut a release now?

**Comment by mdomke** [comment]
I just release version version [3.8.0](https://github.com/mongomock/mongomock/releases/tag/3.8.0). Sorry for the late reply!

**Comment by rcscott** [comment]
🎆 Thanks!
