### ISSUE TITLE
'$ne' on arrays returns documents where any array element is not equal.

### ISSUE THREAD

**Issue by heindsight** [mongomock/mongomock#323]
Queries using `'$ne'` on arrays should return only documents where no element of the array matches the 'rhs' of the `'$ne'` operator. 

For example, in a collection with documents like:
```
{'subtasks': [{'id': 0, 'status': 'pending'}, {'id': 1, 'status': 'done'},...]}
```
The query `collection.find({'subtasks.status': {'$ne': 'pending'}})` should return only documents where no element in the `subtasks` array has `status == 'pending'`:
```
+>>> import pymongo
+>>> real_mongo = pymongo.MongoClient()
+>>> real_coll = real_mongo['test']['foo']
+>>> real_coll.insert([{'subtasks': [{'id': 0, 'status': 'done'}, {'id': 2, 'status': 'failed'}]}, {'subtasks': [{'id': 1, 'status': 'done'}, {'id': 3, 'status': 'pending'}]}, {'subtasks': [{'id': 4, 'status': 'pending'}, {'id': 5, 'status': 'pending'}]}])
[ObjectId('58e52a7397c2bd5b19350e93'), ObjectId('58e52a7397c2bd5b19350e94'), ObjectId('58e52a7397c2bd5b19350e95')]
+>>> [d for d in real_coll.find({'subtasks.status': {'$ne': 'pending'}})]
[{u'_id': ObjectId('58e52a7397c2bd5b19350e93'), u'subtasks': [{u'status': u'done', u'id': 0}, {u'status': u'failed', u'id': 2}]}]
```

However, with mongomock, the query returns all documents where any element in the array has `status != 'pending'`:
```
+>>> import mongomock
+>>> mock_mongo = mongomock.MongoClient()
+>>> mock_coll = mock_mongo['test']['foo']
+>>> mock_coll.insert([{'subtasks': [{'id': 0, 'status': 'done'}, {'id': 2, 'status': 'failed'}]}, {'subtasks': [{'id': 1, 'status': 'done'}, {'id': 3, 'status': 'pending'}]}, {'subtasks': [{'id': 4, 'status': 'pending'}, {'id': 5, 'status': 'pending'}]}])
[ObjectId('58e52a6e97c2bd5b19350e90'), ObjectId('58e52a6e97c2bd5b19350e91'), ObjectId('58e52a6e97c2bd5b19350e92')]
+>>> [d for d in mock_coll.find({'subtasks.status': {'$ne': 'pending'}})]
[{'_id': ObjectId('58e52a6e97c2bd5b19350e90'), 'subtasks': [{'status': 'done', 'id': 0}, {'status': 'failed', 'id': 2}]}, {'_id': ObjectId('58e52a6e97c2bd5b19350e91'), 'subtasks': [{'status': 'done', 'id': 1}, {'status': 'pending', 'id': 3}]}]
```

**Comment by pcorpet** [comment]
Thanks @heindsight for reporting and sorry for the delay in answering. This is a weird behavior of MongoDB and although I can indeed reproduce it, I could not find a good documentation of it. Can you help me find the explanation somewhere please?

**Comment by heindsight** [comment]
Hi @pcorpet, I agree, the documentation around this is not very clear. This behaviour is documented for the `$nin` operator (https://docs.mongodb.com/manual/reference/operator/query/nin/) and although I can't find any mention of it in the documentation, it seems that `$ne` behaves the same.
