### ISSUE TITLE
Document filtering.filter_applies for external, non-testing use

### ISSUE THREAD

**Issue by bpartridge** [mongomock/mongomock#326]
In our production app, we often want to be able to reuse Mongo query language when filtering through lists of dictionaries in memory. Whether it's coming back from Mongo via an autogenerated $or filter and we want to figure out which subclause(s) each one matched, or whether access control rules scanning user-submitted documents on insertion should match the same rules used to query... it would be very useful to be able to reuse the same logic, as it can be elegantly stated in a Mongo query.

Theoretically, you could instantiate a new mongomock database and collection, insert the document in question, and query it. But there's overhead (copying, etc.) involved, particularly if the document to test is large.

Would importing and calling `mongomock.filtering.filter_applies({'foo': 'bar'}, {'foo': 'bar', 'baz': 1})` do the trick? If so, would it be possible to officially stabilize and (trivially) document that API?

Of course, this holds the library to a high standard; if its behavior were to diverge from Mongo's internal behavior, it wouldn't just impact tests, but actual live behavior. But those are the standards we should be aiming for anyways.

If this sounds reasonable, I could submit a PR adding a test for the interface and a note in the README.

**Comment by pcorpet** [comment]
Hi @bpartridge, sorry for the very late answer. Mongomock goal is pretty focused on testing and being an easy replacement for pymongo. I think your usecase would be better covered by a different pattern: if you would extract the filtering part as a different library, that would be used both by yourself and by mongomock then it would be fine. What do you think?
