### ISSUE TITLE
Operators inside $sum aggregate operator are not evaluated

### ISSUE THREAD

**Issue by florianjourda** [mongomock/mongomock#349]
```
mock_db.some_table.aggregate([
        {'$group': {
            '_id': '$someField',
            'countNonEmptyValues': {'$sum': {'$cond': [{'$gt': ['$someOtherField', null]}, 1, 0]}},
        }},
])
```
returns
```
File "/usr/local/lib/python3.6/site-packages/mongomock/collection.py", line 1549, in aggregate
    doc_dict[field] = sum(val_it)
TypeError: unsupported operand type(s) for +: 'int' and 'dict'
```
It seems that `{'$sum': {'$cond': [{'$gt': ['$someOtherField', null]}, 1, 0]}}` is not evaluated (which would give an int) and stays a dict.

**Comment by pcorpet** [comment]
Hi Florian, thanks for reporting. There were several missing features for mongomock to evaluate your expression:
- the first one was indeed the `$sum` not evaluating its argument (this is fixed now)
- a second one which is still there is that `$cond` is not implemented in MongoMock (working on a patch)
- finally the last bit missing is that `$gt` is not good (in mongomock) at comparing values with different types

And of course the error was really not explicit (we try to raise `NotImplementedError` when we know we have blind spots).

Please be patient.
