### ISSUE TITLE
Creating a unique index for collection doesn't check uniqueness in existing documents

### ISSUE THREAD

**Issue by MacHu-GWU** [mongomock/mongomock#351]
``Collection.create_index`` method doesn't check uniqueness in existing document. 

For example:

if we do: ``col.insert([dict(name="Alice"), dict(name="Alice")])``

then do: ``col.create_index([("name", pymongo.ASCENDING)])``, it suppose to raise error in pymongo, but not raises in mongomock.

Plus, the implementation of unique index can be improved by maintaining a set variable, instead of running a find query every times when insert a new document, it's too slow.

@vmalloc

I want to contribute, but having trouble to run tox test locally, looks like your tox setting is very complicate. Just wants to get more detail about how to run the test, in my understanding:

1. fork the repo
2. toggle this forked repo on on travis.ci
3. commit, and test on travis.ci
4. no way to test locally using tox

please correct me

**Comment by pcorpet** [comment]
@MacHu-GWU I agree it's hard to test locally. I tend to run mostly the `test__collection_api.py` locally
```
make test
.env/bin/nosetests -w tests test__collection_api.py
```
as it does not require much dependencies. The whole systems requires a local MongoDB instance, multiple packages installed (pymongo, pyexecjs), so I tend to use Travis.

As for your initial bug, I think you're missing a bit: creating an index should not enforce the uniqueness in documents, except if the index is a "unique index".
```py
>>> col.insert([dict(name="Alice"), dict(name="Alice")])
>>> col.create_index([("name", pymongo.ASCENDING)], unique=True)
pymongo.errors.DuplicateKeyError: E11000 duplicate key error collection: test.test index: name_1 dup key: { : "Alice" }
```

**Comment by MacHu-GWU** [comment]
@pcorpet Thank you for your reply! it is very helpful!
