### ISSUE TITLE
aggregate $unwind does not handle dict parameter

### ISSUE THREAD

**Issue by revanthreddy** [mongomock/mongomock#354]
I am trying to run tests using mockmongo around my dao function which is running an aggregate command (below)

```py
collection1.aggregate([
            {
                "$unwind": {
                    "path": "$collection2",
                    "preserveNullAndEmptyArrays": True
                }
            },
            {
                "$lookup": {
                    "from": "collection2",
                    "localField": "collection2",
                    "foreignField": "_id",
                    "as": "collection2"
                }
            },
            {
                "$match": {"_id": id, "deleted": False}
            }
        ])
```

But the test fails with
'**ValueError: $unwind failed: exception: field path references must be prefixed with a '$' '{'path': '$randomcollection', 'preserveNullAndEmptyArrays': True}**'

Any help would be greatly appreciated

I am using 
mockmongo = 3.8.0
pymongo=3.4.0
mongo=3.4.9

**Comment by pcorpet** [comment]
Hi @revanthreddy, sorry for the delay in the response. Mongomock does not handle the parameter of `$unwind` as an object yet. The error message is not clear: I'll try to fix at least this quickly.
