### ISSUE TITLE
Support for Cursor.explain method?

### ISSUE THREAD

**Issue by domeniconappo** [mongomock/mongomock#363]
Is there any chance to implement/support explain() method for Cursor? In this way, one can create tests to evaluate indexes usage

**Comment by pcorpet** [comment]
Hi @domeniconappo, this seems not obvious as mongomock does not use index. Usually test data is so light that all operations are super fast so we did not implement any complex index logic (except to maintain uniques).

Ping @vmalloc, the intial author, who might have a different view on this.

**Comment by domeniconappo** [comment]
@pcorpet 
Ok, got it. It makes sense. 
Thanks for clarification!
