### ISSUE TITLE
Consider new pypi release

### ISSUE THREAD

**Issue by zachmullen** [mongomock/mongomock#376]
I'm not sure what the normal release cycle is for mongomock, but there have been a bunch of nice changes merged recently. Is there a release planned for the near future?

**Comment by vmalloc** [comment]
I can publish a release in the next few days. I’m not sure about the stability of the current branch though and I will not have the capacity to handle a lot of fixes at once

**Comment by touilleMan** [comment]
@vmalloc you can release a new major version so people would be more likely to stick to the previous one if something goes wrong

To give you feedback about the stability of the current master branch, we are running mongomock for testing in a non trivial web application (code base around 70k SLOC) with 2000+ tests ;-)

**Comment by vmalloc** [comment]
Ok, just pushed the tag, should be on pypi within the next 15 minutes. Stay tuned for new issues :-)

**Comment by touilleMan** [comment]
:+1:

**Comment by zachmullen** [comment]
Thanks!
