### ISSUE TITLE
PyMODM compatibility

### ISSUE THREAD

**Issue by CalgaryMichael** [mongomock/mongomock#382]
I have been attempting to create an API wrapper to mock out query sets for PyMODM using this library. Unfortunately, there are a few areas of incompatibility between these two libraries that will raise runtime errors. The good news is that most of the issues that I have found are a simple fix of adding `**kwargs` to some function parameters, and one instance of needing to cast a generator to a list.

I would love for this package to be compatible with PyMODM. I have the fixes for all the hiccups that I know of, so creating a pull request for this would be quick. Let me know what you think!

**Comment by vmalloc** [comment]
PRs are very welcome! I try to go through them in a timely manner, but usually I get to them within a few days. Make sure you include unit tests to those changes on separate PRs, and follow the [mocking guideline in the README](https://github.com/mongomock/mongomock#important-note-about-project-status--development)

**Comment by pcorpet** [comment]
@CalgaryMichael, please see cb5eb8c, it should have included all the basics you were after. If there are still incompatibilities, please reopen this bug and add details.
