### ISSUE TITLE
Projections does not work

### ISSUE THREAD

**Issue by joinsunil** [mongomock/mongomock#385]
In my code, I have used projection, while writing test cases I encounter with a bug.

```
           this.database.collection(collectionName)
                .find(queryObj, projectionObj, optionObj).toArray((error, docs) => {
                    if (error) {
                        return reject(error);
                    }
                    console.log('docs', docs, 'projectionObj', projectionObj);
                });
            });
```

In console I am getting this --`docs [ { 'license.agent.agentCode': undefined } ] projectionObj { 'license.agent.agentCode': 1 }`

But if I remove projection object it is giving me correct data.

**Comment by pcorpet** [comment]
Hi @joinsunil, I'm a bit confused by your bug report as it seems to be using `Javascript` syntax whereas mongomock is a `Python` library.

I've tried to check the python equivalent of your example with mongomock and it seems to work with version `3.9.0` and further. Please update your bug report with:
- python code if possible
- the initial values inserted in the collection
- the expected value

**Comment by sunil-srma** [comment]
@pcorpet Yes you are correct. I posted in wring repository.

**Comment by sunil-srma** [comment]
Closed !
