### ISSUE TITLE
Aggregation framework $project does not work on fields within nested documents

### ISSUE THREAD

**Issue by boxmansf** [mongomock/mongomock#397]
When using {'$projection' : {'doc_field.subfield': 1}} in an aggregation pipeline, this doesn't work:
  File ".../lib/python2.7/site-packages/mongomock/collection.py", line 1627, in aggregate
    out_collection = _extend_collection(out_collection, field, value)
  File ".../lib/python2.7/site-packages/mongomock/collection.py", line 1506, in _extend_collection
    doc[field] = _parse_expression(expression.copy(), doc)
AttributeError: 'int' object has no attribute 'copy'

**Comment by adrianocanofre** [comment]
I have the same problem when using [aggregate](https://docs.mongodb.com/manual/aggregation/)

**Comment by pcorpet** [comment]
I think you are both writing about the same feature: subfields in [$project](https://docs.mongodb.com/manual/reference/operator/aggregation/project/). It is indeed unsupported yet, however the error should be clearer about it. I've worked on a first fix to give the right exception, and might follow up with the actual solution.

**Comment by pcorpet** [comment]
@boxmansf Please review #475.
