### ISSUE TITLE
Api call that uses mongomock causes 500 INTERNAL SERVER ERROR but works with Mongodb

### ISSUE THREAD

**Issue by daniellepintz** [mongomock/mongomock#400]
The following code causes an error when using mongomock, but not when using mongodb:

        result = self.logs_engine.LogCollection.objects(
            __raw__={'app_id': app_id, "results": {
        "$gt": [{"$size": "results"}, 0]}}).only(
            "user_input", "app_id", "results", "date_time")
        **print(result)**

The error is: TypeError: '>' not supported between instances of 'dict' and 'dict'

**Comment by pcorpet** [comment]
Hi @daniellepintz , your code contains a lot of keywords I'm not familiar with that are probably linked to your own framework (`LogCollection`, `objects`, 'app_id`). Can you try to untangle it and give an example that would illustrate the issue with a direct call to `pymongo` or `mongomock` please? Alternatively can you give us more details on what LogCollection is?

**Comment by pcorpet** [comment]
OK got it, I think you are using `mongoengine` and that the equivalent is simply:
```py
db.a.find({
  "app_id": app_id,
  "results": {
    "$gt": [{"$size": "results"}, 0],
  }
})
```
And I was indeed able to reproduce having an error in `mongomock` but not using `pymongo` + MongoDB.

**Comment by pcorpet** [comment]
Note that the initial query probably does not work as the author intended: the `$size` is not computed as an operator at all, however it should not crash. Working on a fix.

**Comment by pcorpet** [comment]
A more legitimate use of a query that indeed fail would be:
```py
db.a.insert_many([
 {'_id': 1, 'field': {'subfield': 1}},
 {'_id': 2, 'field': {'subfield': 2}},
])

db.a.find({'field': {'$gt': {'subfield': 1}}})
```
In `pymongo` + MongoDb, this returns the second element, whereas it crashes today with `mongomock`.

**Comment by daniellepintz** [comment]
Thanks so much for the fix!
