### ISSUE TITLE
Mongomock allows saving a value of type "set" for a key, while this should fail

### ISSUE THREAD

**Issue by boxmansf** [mongomock/mongomock#416]
On real mongo the following error is raised (for example when setting a key to set(['a', 'b', 'c']):
InvalidDocument: Cannot encode object: set([u'a', u'b', u'c'])

**Comment by pcorpet** [comment]
Hmm I cannot reproduce, can you provide a simple code that passes but should fail please?

I just run (in Python 3.6.5):
```py
import mongomock
mongomock.MongoClient().db.test.insert_one({'a': set(['a', 'b', 'c'])})
```

and I got the error
`bson.errors.InvalidDocument: Cannot encode object: {'b', 'c', 'a'}`

**Comment by boxmansf** [comment]
I had this in python 2.7.12 and with an update call, rather than insert

**Comment by pcorpet** [comment]
Got it. I was indeed able to reproduce with an `update` or a `replace. I've sent a fix for review.
