### ISSUE TITLE
collection.insert_many raises BulkWriteError incorrectly (incorrect arguments)

### ISSUE THREAD

**Issue by boxmansf** [mongomock/mongomock#425]
Way to reproduce:
1. Call insert_many with documents containing a duplicate key on a collection that has a unique index on some key
2. This will cause BulkWriteError('batch op errors occurred') to be raised
3. Following error occurs:
  File "/work/env/lib/python2.7/site-packages/mongomock/collection.py", line 319, in insert_many
    raise BulkWriteError('batch op errors occurred')
` File "/work/env/lib/python2.7/site-packages/pymongo/errors.py", line 210, in __init__
    "batch op errors occurred", 65, results)
  File "/work/env/lib/python2.7/site-packages/pymongo/errors.py", line 131, in __init__
    error_labels = details.get('errorLabels')
AttributeError: 'str' object has no attribute 'get'`

BulkWriteError should not be receiving a string.

**Comment by pcorpet** [comment]
Hi @boxmansf, thanks for reporting. This bug has already been fixed by #398, however it's not released yet. I'm trying to get some few more fixes before next release, but if it's urgent you can use the latest version of mongomock directly from github.
