### ISSUE TITLE
TypeError: find() got an unexpected keyword argument 'session'

### ISSUE THREAD

**Issue by armudgal** [mongomock/mongomock#426]
Hi, got this error when trying to execute this

`doc = collection.find_one(projection={"_id": 1}, session=self._session)`

Error:
`TypeError: find() got an unexpected keyword argument 'session'`

I think the fix would be to add `session = None` in the respective `find()` function

**Comment by armudgal** [comment]
Just saw this: https://github.com/mongomock/mongomock/commit/f4b81603c1e16e318c660ad36d524c733894aefc

Would you guys be releasing a new version soon? Thank you

**Comment by pcorpet** [comment]
I'd love to. However I am a new maintainer and haven't done any release yet. I've pinged @mdomke by email.

**Comment by armudgal** [comment]
Thanks, much appreciated
