### ISSUE TITLE
TypeError: list_indexes() got an unexpected keyword argument 'session'

### ISSUE THREAD

**Issue by armudgal** [mongomock/mongomock#435]
Hi, currently `collection.list_indexes()` does not expect a `session` parameter due to which this `TypeError` is thrown, could you please check it.
Thanks

**Comment by armudgal** [comment]
Hi,
Thanks for responding and fixing the bug so quickly, is there an estimate when will you be releasing the next version?
Again, Thank you

**Comment by pcorpet** [comment]
I just did. Thanks for your support.
