### ISSUE TITLE
$bucket operator for the aggregation pipeline is not implemented

### ISSUE THREAD

**Issue by rillomas** [mongomock/mongomock#441]
I got the following error while running a query using `$bucket`.

```
NotImplementedError: $bucket is not a valid operator for the aggregation pipeline. See http://docs.mongodb.org/manual/meta/aggregation-quick-reference/ for a complete list of valid operators.
```

I believe https://github.com/mongomock/mongomock/blob/develop/Missing_Features.rst needs to get updated.

version: 3.11.1

**Comment by pcorpet** [comment]
Thanks @rillomas I've updated the documentation and the message error as well. It now says it's a valid operator, but not implemented in mongomock yet.
