### ISSUE TITLE
list_indexes() should return a dictionary as index key.

### ISSUE THREAD

**Issue by Colin-b** [mongomock/mongomock#449]
Hi,

Since release 3.12.0, Collection.list_indexes() now returns something.

I am expecting the value linked to the index 'key' to be a dictionary (see current pymongo usage: https://github.com/mongodb/mongo-python-driver/blob/master/pymongo/collection.py#L2197) but it is provided as a list of tuple by mongomock: https://github.com/mongomock/mongomock/blob/develop/mongomock/collection.py#L1364

Unfortunately I don't have enough time right now to dig into it but it seems that the solution would be to convert this list of tuple to a dictionary (dict(my_list_of_tuples) should do the trick) ?

Thanks

**Comment by pcorpet** [comment]
Hi @Colin-b thanks for reporting and sorry that we released 3.12.0 without testing thoroughly the behavior of `list_indexes`. I've now added a test to ensure consistency with `pymongo` for that method.

It will be fixed in the next release.

**Comment by Colin-b** [comment]
No worries, bugs are part of every project life.

Thanks for the prompt response and fix, mongomock is a great project.
