### ISSUE TITLE
collection_names is deprecated

### ISSUE THREAD

**Issue by moonso** [mongomock/mongomock#453]
As mentioned [here](
http://api.mongodb.com/python/current/api/pymongo/database.html#pymongo.database.Database.collection_names) this will be replaced by [list_collection_names](
http://api.mongodb.com/python/current/api/pymongo/database.html#pymongo.database.Database.list_collection_names)

**Comment by pcorpet** [comment]
Fixed by #454 . Thanks a lot @moonso for reporting AND fixing!
