### ISSUE TITLE
method find_one with projection not return nested document [v3.12]

### ISSUE THREAD

**Issue by lukaszkiszka** [mongomock/mongomock#456]
In database I have document:
```javascript
{
'_id': ObjectId('5bbaf01a93d3e0147981ba4d')
'name': 'test schedule', 
'mail_subject': 'Mail subject', 
'recipients': ['test@test.com'], 
'reports': [
{'report_id': ObjectId('5b7e6af3ded0de64bf1f40c8'), 'format': 'csv'}, 
{'report_id': ObjectId('5b7e6af3ded0de64bf1f40c8'), 'format': 'pdf'}
], 
'periodic_task_id': ObjectId('5bbaf01a93d3e0147981ba4e')
}
```
When I run query:
```python
result = ctx.mongo.db.report_schedule_definitions.find_one({'_id': ObjectId(Id)}, {'field': 0})
```
Then result is (not returns all document fields):
```javascript
{'name': 'test schedule', 'mail_subject': 'Mail subject', 'periodic_task_id': ObjectId('5bbaefe893d3e0141297f898'), '_id': ObjectId('5bbaefe893d3e0141297f897')}
```
When I run the same query without projection:
```python
result = ctx.mongo.db.report_schedule_definitions.find_one({'_id': ObjectId(Id)})
```
then query return corect document.

As you see when projection is setting in query then query not return nested object fields (recipients, reports fields). When I debug code I see in `collection.py` method `_project_by_spec` commnet `# copy only scalar values` - in this palace mockmongo omnit my nested object fields. why? 

In mockmongo v3.10 this projection works fine.

**Comment by pcorpet** [comment]
@lukaszkiszka Thanks for reporting. The code for projecting has been modified several times recently and we don't have a good test coverage for some features. Sorry for the regression.
