### ISSUE TITLE
mongomock does not validate the find filter when running on an empty collection

### ISSUE THREAD

**Issue by boxmansf** [mongomock/mongomock#457]
In real mongo, when using a {'$or': []} query set, the following error is emitted:

[0m >               response = {'code': 2, 'codeName': 'BadValue', 'errmsg': '$and/$or/$nor must be a nonempty array', 
....
[0m >               raise OperationFailure(msg % errmsg, code, response)
[0m E               OperationFailure: $and/$or/$nor must be a nonempty array

**Comment by pcorpet** [comment]
Hi @boxmansf , thanks for reporting. Can you please be more precise on the way you use the `$or` operation please? I do get this error:

```py
>>> import mongomock
>>> c = mongomock.MongoClient().db.test
>>> c.insert_one({})
>>> c.find_one({'$or': []})
pymongo.errors.OperationFailure: BadValue $and/$or/$nor must be a nonempty array
```

**Comment by boxmansf** [comment]
@pcorpet Please try running it on an empty collection (skip the insert_one({}) call) - that call doesn't fail on mongomock.

**Comment by pcorpet** [comment]
Fair enough. I think this is true about any query that is not well formed: on an empty collection we do not check the validity of the query yet.
