### ISSUE TITLE
insert_many fails insertion if called with a generator

### ISSUE THREAD

**Issue by gpetretto** [mongomock/mongomock#460]
Calling the `insert_many` method of a collection and giving a generator as an argument results in no document being inserted in the db, at variance with what happens in pymongo. 
Here is a snippet of code demonstrating the problem:

```python
import mongomock
import pymongo

data = (x for x in [{"a": 1}, {"b": 2}])

client = mongomock.MongoClient("mongodb://host1/foo")
db = client.get_default_database()

coll = db.test_coll
coll.insert_many(data)

print("results in mongomock: ", coll.find().count())

data = (x for x in [{"a": 1}, {"b": 2}])

client = pymongo.MongoClient("localhost", 27017)
db = client.test_db
coll_mongo = db.test_coll
coll_mongo.remove()

coll_mongo.insert_many(data)
print("results in pymongo: ", coll_mongo.find().count())
```
with its output:

> results in mongomock:  0
> results in pymongo:  2

The problem originates from the fact that in `insert_many` the generator is iterated to validate its content. So, when it is passed to the `_insert` method, the generator has already been exhausted and no document is inserted in the db.

A simple fix could be to just generate the list if it is a generator:
```python
    def insert_many(self, documents, ordered=True, session=None):
        if not isinstance(documents, Iterable) or not documents:
            raise TypeError('documents must be a non-empty list')
        if isinstance(documents, types.GeneratorType):
            documents = list(documents)
        for document in documents:
            validate_is_mutable_mapping('document', document)
        return InsertManyResult(self._insert(documents, session), acknowledged=True)
```

**Comment by pcorpet** [comment]
HI @gpetretto, thanks for reporting. It's a pity: we have a test in place that checks the behavior of insert_many on a generator, except it does not check properly that the documents were actually inserted.

I like your fix, and I think you can always wrap it to a list even if it's not a generator.

**Comment by gpetretto** [comment]
Thanks for the quick reply and the fix!
