### ISSUE TITLE
Mongomock usage raises UserWarning: "collection_names is deprecated. Use list_collection_names instead"

### ISSUE THREAD

**Issue by boxmansf** [mongomock/mongomock#461]
mongomock/database.py:41: UserWarning:

  collection_names is deprecated. Use list_collection_names instead.

**Comment by pcorpet** [comment]
Can you tell me what is the issue here?

I think this is working as intended: it is consistent with pymongo, see https://github.com/mongodb/mongo-python-driver/blob/master/pymongo/database.py#L709

**Comment by boxmansf** [comment]
Sorry - it's my mistake - the warning is due to our code usage of mongomock...
