### ISSUE TITLE
collection.with_options with default write_concern is choking

### ISSUE THREAD

**Issue by mcsloe** [mongomock/mongomock#465]
Using mongomock and mongoengine (0.16.1) results in mongomock raising a NotImplementedError.
See https://github.com/MongoEngine/mongoengine/issues/1953.

This is currently making it impossible to use mongomock in unit tests.

Is there any chance this can be changed in mongomock or can anyone suggest a simple work-around?

**Comment by pcorpet** [comment]
Hi @mcsloe sorry that mongomock is blocking your unit tests, and thanks for reporting.

Note that we should accept a default WriteConcern (i.e. with no specific options). If you choke on the NotImplementedError, either we have a bug or you are setting a specific WriteConcern somewhere. Can you check in your code if you are setting some write concerns at one point? I know that at one point there was a bug because `mongoengine` was recreating a WriteConcern and that we didn't manage to compare it with the default option, but it should be fixed in v3.13.

If you can find which option you are setting, I might implement it/or accept the current implementation as valid for this write concern.

**Comment by pcorpet** [comment]
After a little digging, it seems that https://github.com/MongoEngine/mongoengine/blob/34e3e45843ef0475824b79b3405285a2d75d7648/mongoengine/document.py#L367 is setting it to `{'w': 1}` which according to the [doc](https://docs.mongodb.com/manual/reference/write-concern/) is the default.

So I'll make sure to fix accept this value as a default. Sorry about that.

**Comment by stefanvanburen** [comment]
Would it be possible to cut a release with this change? We're looking to upgrade to `0.16.1` of mongoengine and would prefer to get mongomock to a tagged version as well.

thanks for the project!

**Comment by pcorpet** [comment]
@svanburen I'd be happy to. Can you please first check that my fix actually solves your issue?

**Comment by wdoekes** [comment]
:+1: with 18e5ad6 all my mongo tests work again.

```
$ ./manage.py test tests.test_mongo
...
FAILED (errors=6)

$ curl 'https://github.com/mongomock/mongomock/commit/18e5ad6f9287a8587a56c799e098f36ac836510d.patch' | patch -p1

$ ./manage.py test tests.test_mongo
...
Ran 6 tests in 0.028s

OK
```

**Comment by pcorpet** [comment]
Thanks for checking. Released as [v 3.14.0](https://github.com/mongomock/mongomock/releases/tag/3.14.0).

**Comment by stefanvanburen** [comment]
Fixes my tests as well. Thanks for the quick turnaround!

**Comment by boxmansf** [comment]
@pcorpet I seem to be getting a similar error after upgrading to v 3.14.0:

colc.with_options(write_concern = 1).update_one(..)
NotImplementedError: write_concern is a valid parameter for with_options but it is currently not implemented in Mongomock

Should it be supported or is this a different usecase (should I open a new issue?)

**Comment by pcorpet** [comment]
I think the issue here is that `write_concern` param should be a `WriteConcern` object, not an `int`. It would still be nicer if the message error would tell you that :-)

**Comment by boxmansf** [comment]
Sorry, it's my mistake earlier on (i wrote the 1 value incorrectly).
The actual code looks like this:
write_concern = WriteConcern(w=2, wtimeout = 60000)
colc.with_options(write_concern=write_concern).update_one(...)

**Comment by pcorpet** [comment]
OK, that makes more sense.

This is a different write concern and for now mongomock does not support it (as stated in the error). You can open another issue for that feature request. Please give a hint on how you think mongomock should behave with a different write_concern.

**Comment by boxmansf** [comment]
Thanks, opened #472
