### ISSUE TITLE
Is there any plan to add "$in" to aggregation  or replacement for the "$in" 

### ISSUE THREAD

**Issue by Motor-taxi-master-rider** [mongomock/mongomock#466]
When I try to add some `set in` logic in the *$project* pipeline like:
```
{'$in': ['impressive', '$tags']}
```
It will raise an exception says that *$in*  is unrecognized expression in *aggregate.py* line 150. Seems because it is not included in the *set_operators* list. I know the *set_operators* is not implemented yet, just want to know if *$in* will be included in the list.
If there is not a replacement for the *$in* operator to do the set operation, it will be kind of you if you tell me!

**Comment by pcorpet** [comment]
HI @Motor-taxi-master-rider, thanks for reporting. It's a but that we report it as an OperationFailure, so I'll fix this now. And the actual implementation should be quite easy so it might follow quite soon.

**Comment by pcorpet** [comment]
@Motor-taxi-master-rider please review the PR #467.

**Comment by pcorpet** [comment]
@Motor-taxi-master-rider please review the PR #467.

**Comment by Motor-taxi-master-rider** [comment]
> @Motor-taxi-master-rider please review the PR #467.

Thanks for your quick fix!

**Comment by pcorpet** [comment]
It's not fixed yet, until #467 gets reviewed and merged in develop.
