### ISSUE TITLE
Microseconds rounded when saving objects

### ISSUE THREAD

**Issue by wbaelen** [mongomock/mongomock#468]
When saving an document object with a time field and comparing to the time specified in the test, they are off by microseconds in Python2.7.

**Comment by pcorpet** [comment]
I think that is consistant with what Mongo does: BSON dates have milliseconds precision, not below https://docs.mongodb.com/manual/reference/bson-types/

So here `mongomock` is doing exactly what using `pymongo` and a MongoDB server would do.

Please reopen if I got it wrong somewhere.
