### ISSUE TITLE
Implement Database.command, at least the ping command

### ISSUE THREAD

**Issue by Colin-b** [mongomock/mongomock#469]
My application health check is sending a ping command but I noticed command method is not implemented in Database, leading to command being interpreted as a Collection.

Maybe we could foresee a first implementation only handling 'ping' command and returning {'ok': 1.0} ?

**Comment by pcorpet** [comment]
Hi @Colin-b, thanks for reporting. We should at least implement a placeholder that raises a `NotImplementedError` and once we have that, it would be trivial to implement the ping command.

I'll keep this one as a bug until we get the `NotImplementedError`.

**Comment by pcorpet** [comment]
@Colin-b please review #471.

**Comment by Colin-b** [comment]
Thanks a lot for the quick fix! Should I let you close this issue once merged?

**Comment by pcorpet** [comment]
GitHub will do it automatically because of the string "Fixes #469" in the commit message.
