### ISSUE TITLE
KeyError in aggregation

### ISSUE THREAD

**Issue by ulyssejdv** [mongomock/mongomock#470]
When we execute the aggregate command with a key who not exists that raise an KeyError exception.

Exemple :

Data :
```
 [
            {'k1': 'value1', 'k2': 'value2', 'k3': 'value3'},
            {'k1': 'value1', 'k2': 'value22', 'k3': 'value3'},
            {'k1': 'value11', 'k2': 'value2', 'k3': 'value3'},
            {'kk1': 'value11', 'k2': 'value2', 'k3': 'value3'},
 ] 
``` 

Command :
`db.my_collection.aggregate([{'$project': {}}, {'$group': {'_id': {'k1': '$k1'}, 'k2': {'$addToSet': '$k2'}}}])`

Result : 

```
obj = {'_id': ObjectId('5bf3bfd66284912384ef5af0'), 'k2': 'value2', 'k3': 'value3', 'kk1': 'value11'}
key = 'k1'

    def recurse_embedded(obj, key):
        ret = obj
        for k in key.split('.'):
>           ret = ret[k]
E           KeyError: 'k1'
```

**Comment by pcorpet** [comment]
Hi @ulyssejdv, thanks for reporting. I agree it's indeed a bug: the last row should be assigned to the group with ID `None`.

**Comment by ulyssejdv** [comment]
Thank you @pcorpet
