### ISSUE TITLE
mongomock does not support with_options(write_concern=...)

### ISSUE THREAD

**Issue by boxmansf** [mongomock/mongomock#472]
See below syntax:
write_concern = WriteConcern(w=2, wtimeout = 60000)
colc.with_options(write_concern=write_concern).update_one(...)

I would suggest implementing by just ignoring this param when passed to with_options, as mongomock is not simulating a cluster.

**Comment by pcorpet** [comment]
Thanks @boxmansf. Note that it cannot completely be ignored as:
`colc.with_options(write_concern.WriteConcern(w=2, wtimeout=60000)).write_concern` should return the new write concern, however it should still access the same data.

I'm working on a refactor to decorrelate the Collection object from the actual data and indices. Once that one is done, it will be trivial to do what you're suggesting.

**Comment by pcorpet** [comment]
@boxmansf please review #474
