### ISSUE TITLE
$sum and $add inside aggregate operator yield incorrect value

### ISSUE THREAD

**Issue by gmauch** [mongomock/mongomock#473]
Suppose I have a collection with this single document:

{
	"_id" : ObjectId("5bf5bd7e06366d73684a80b5"),
	"name" : "first",
	"base_value" : 100,
	"values_list" : [
		{
			"updated_value" : 5
		},
		{
			"updated_value" : 15
		}
	]

and I wish to sum the _base_value_ with the last _updated_value_ value in the _values_list_. the following query would achieve this and output the results to a new collection (through the _$out_ operator):

db.collection_name.aggregate({'$project': {'name': 1,
                     'base_value': {'$sum': ['$base_value', {'$arrayElemAt': ['$values_list.updated_value', -1]}]}
                      },
                      {'$out': 'new_collection_name'}
        }

When running this query on a local instance of MongoDB, the result for the new _base_value_ is 115 (being 100 the current value and 15 the last value on the list). However, when running using Mongomock (versions 3.12.0 and 3.14.0) the result is 100. I also tried replacing the $sum for a $add, but the problem keeps happening.
I read other open issues and this [one seems](https://github.com/mongomock/mongomock/issues/349) related, but I'm not sure is the same problem.
At last, I attached a Python script that shows this problem happening, which should be useful to test and validate the error condition.
[mongomock_test.txt](https://github.com/mongomock/mongomock/files/2608045/mongomock_test.txt)

**Comment by pcorpet** [comment]
@gmacon , oops, that's a bad one. I'll take a look ASAP.

**Comment by pcorpet** [comment]
Hmm, I believe the trouble is that `$values_list.updated_value` is not a real array but a generated one (I didn't know that MongoDB handled those as array). I actually get a `TypeError`. But the implementation of the `$project` stage is really screwed up anyway. It's time I fix it.
