### ISSUE TITLE
Aggregation framework for $sample does not support sizes larger than collection size

### ISSUE THREAD

**Issue by darwinlyang** [mongomock/mongomock#476]
When I try to use $sample with a size of 1 on an empty collection I get an IndexError as the sequence for random is empty. Normally, MongoDB would return nothing in this situation. 

In addition, when using $sample, if a size of 5 is used with a collection size of only 1. The aggregation framework should only return the 1 document but it seems that your code may potentially return the 1 document five times.

**Comment by pcorpet** [comment]
Hi @DarwinLYang, thanks for reporting. I'll fix it ASAP.
