### ISSUE TITLE
multiple bulk.find.update(..) don't raise BulkWriteError

### ISSUE THREAD

**Issue by ronyf** [mongomock/mongomock#477]
Running the following code

	bulk = agent_class.get_collection().initialize_unordered_bulk_op()
	for bulk_op in bulk_data:
		bulk.find(bulk_op['query']).upsert().update(bulk_op['update'])
	result = bulk.execute()

raises `DuplicateKeyError` instead of `BulkWriteError`
while `pymongo` raises `BulkWriteError`.

looks like it ignores the whole `unordered` setting, which means that it should continue despite the dup key errors...

while debugging the issue, I noticed that `mongomock`'s `Collection._update(..)` function receives a single value both in `spec` and `document`, which means that `Collection_data(..)` receives data of type `dict` instead of `list`.

I would expect the same behavior on both pymongo and mongomock..

**Comment by ronyf** [comment]
Ah! All that happened because `ordered=False` is not supported yet..

    NotImplementedError: Unordered mode is a valid MongoDB operation; however Mongomock does not support it yet.

**Comment by pcorpet** [comment]
@ronyf Thanks for reporting. mongomock should at least complain properly about that. I'll fix that.

Do you think you could implement the unordered mode in a PR?

**Comment by pcorpet** [comment]
According to the [doc](https://docs.mongodb.com/manual/reference/method/db.collection.initializeUnorderedBulkOp/), I believe it's mostly a matter of applying other operations even if one of them fails. I'll give it a try.
