### ISSUE TITLE
Bulk operation doesn't raise an exception as a mongod instance would.

### ISSUE THREAD

**Issue by thestick613** [mongomock/mongomock#481]
This code is wrong, i don't neet to set the _id again in the update document:

    bulk = col.initialize_unordered_bulk_op()
    bulk.find({"_id": {"a": 1, "b": 2}}).upsert().update({"$set": {"field": "value", "_id": {"a": 1, "b": 2}}
    bulk.execute()

Mongomock doesn't complain about it, and does as it is requested. However, a real mongod instance throws this:

    {'writeErrors': [{'index': 0, 'code': 66, 'errmsg': "Performing an update on the path '_id' would modify the immutable field '_id'", 'op': SON([('q', {'_id': {'a': 1, 'b': 2}})

This isn't really a big deal, but it will make mongomock closer to the original.

**Comment by pcorpet** [comment]
Hi @thestick613 , thanks for reporting. It's a bug indeed and mongomock should yell early on, otherwise it keeps its store in an inconsistant state.

**Comment by pcorpet** [comment]
Actually your code revealed a bug (that you can change the ID). I'm not sure I'll be able to detect the problem when you're trying to set the ID by the same value. MongoDB is complaining probably because your two dicts don't have the keys in the same order (order of keys in dict is not stable).

**Comment by pcorpet** [comment]
I think I'm only going to fix the bug where you want to change the ID and I can detect that it's a different value. In your example, it's not obvious why MongoDB detects a different value.
