### ISSUE TITLE
Cannot update document with id 0 or ''

### ISSUE THREAD

**Issue by zozoens31** [mongomock/mongomock#482]
When updating a document if it has _id with a falsy value (`0`, `False`, `''`, ...) it raises a KeyError:

To reproduce:
```python
    db.collection.insert_one({'_id': ''})
    db.collection.update_one({'_id': '', {'a': 1}}  # raises KeyError: '_id'
    db.collection.find_one({'_id': ''})
```
Expected behavior:

the previous code should return
```python
    {'_id': '', 'a': 1}
```

**Comment by pcorpet** [comment]
Hi Cyrille, thanks a lot for reporting... and sending a fix. Add yourself to the contributors in a separate PR if you wish.
