### ISSUE TITLE
Collection name checks are not performed

### ISSUE THREAD

**Issue by Colin-b** [mongomock/mongomock#484]
Hi,

I am using the creation of a Collection to ensure that provided name is a valid one,
Could we ensure that pymongo checks are also performed on mongomock when creating a new Collection ?

You can refer to pymongo code here: https://github.com/mongodb/mongo-python-driver/blob/master/pymongo/collection.py#L158

This change will introduce regression for some users but in my point of view the current behavior is more a side effect than an expected one (as test case would fail with pymongo).

However I would understand the negative impact for users using mongomock as a production in-memory database (if there is any?).

I can submit a PR if you do not have time to look into this, just ask me to :)

**Comment by pcorpet** [comment]
Hi @Colin-b, this is indeed a bug. Note that some of the checks are done when trying to rename, others are done when trying to create a collection. Let me fix that.

**Comment by Colin-b** [comment]
Thanks a lot !
