### ISSUE TITLE
aggregation $min and $max ignore falsy values

### ISSUE THREAD

**Issue by jessekv** [mongomock/mongomock#486]
In these lines:
https://github.com/mongomock/mongomock/blob/b39e6f335dbbfb99a43a857b7dea43f069e72e33/mongomock/aggregate.py#L115-L116

the `$min` and `$max` operators ignore falsy values, e.g. when `val` is zero, it evaluates to `False` and is ignored. 

To demonstrate the problem: 

```python
>>> my_min = lambda values: min(val or 100 for val in values)
>>> my_min([2,3,4])
2
>>> my_min([2,0,4])
2
```

**Comment by pcorpet** [comment]
Hi @vdwees, thanks for reporting the bug. I'll fix this ASAP.
