### ISSUE TITLE
The $sort modifier of the $push operator is not implemented

### ISSUE THREAD

**Issue by ghost** [mongomock/mongomock#492]
It should be possible to push and sort (and also slice, which would happen after the sort) in one operation. Sort seems to be simply ignored when trying to do so. Test case:

    def test__update_push_and_sort(self):
        self.db.collection.insert_one({'a':
                                       {'b': [{'value': 3},
                                              {'value': 1},
                                              {'value': 2}]}})
        self.db.collection.update_one({}, {'$push': {'a.b': {'$each': [{'value': 4}],
                                                             "$sort": {'value': 1}}}})
        self.assertEqual({u'b': [{u'value': 1}, {u'value': 2}, {u'value': 3}, {u'value': 4}]},
                         self.db.collection.find_one()['a'])

**Comment by pcorpet** [comment]
Hi @vainu-arto it's indeed a missing feature in Mongomock. However it's a bug that the lib is not warning you about it.

**Comment by pcorpet** [comment]
I've fixed the code to properly report that the feature is not implemented yet.

The next step would be to implement the actual feature.

**Comment by pcorpet** [comment]
@vainu-arto please review #494
