### ISSUE TITLE
MongoMock doesn't error on bad top level operator

### ISSUE THREAD

**Issue by chdsbd** [mongomock/mongomock#495]
If I run the following snippet with a real mongo database, I get: "pymongo.errors.OperationFailure: unknown top level operator: $ne"
```python
{'$and': [{'$ne': False}]}
```

With MongoMock, I receive no error.

I think MongoMock should raise a similar error in this case.

**Comment by chdsbd** [comment]
Fun fact, this is a bug in the mascot implementation too!

**Comment by chdsbd** [comment]
Thanks for the quick response and fix @pcorpet!

**Comment by pcorpet** [comment]
Thanks Christopher for reporting.
