### ISSUE TITLE
Implement '$setUnion' in the aggregation

### ISSUE THREAD

**Issue by YuvalPruss** [mongomock/mongomock#507]
I have a mongo operation that includes the `$setUnion` pipeline operation in an aggregation operation. I received this error:

    NotImplementedError: Although '$setUnion' is a valid set operator for the aggregation pipeline, it is currently not implemented in Mongomock.

Can u implement this?

**Comment by pcorpet** [comment]
@YuvalPruss Please take a look at #510 and approve it before I merge it.

**Comment by YuvalPruss** [comment]
@pcorpet Seems OK 👍
