### ISSUE TITLE
'list_database_names' in mongo client is not supported

### ISSUE THREAD

**Issue by boxmansf** [mongomock/mongomock#508]
This is a new function that was added in pymongo 3.6
http://api.mongodb.com/python/current/api/pymongo/mongo_client.html#pymongo.mongo_client.MongoClient.list_database_names

(The currently existing 'database_names' function is deprecated)

**Comment by pcorpet** [comment]
@boxmansf Thanks for reporting, please review #509.

**Comment by boxmansf** [comment]
@pcorpet Approved the PR, thank you for the quick turnaround adding this !
