### ISSUE TITLE
$eq and $ne behaviour is different from Mongo for array fields

### ISSUE THREAD

**Issue by NazarTopolsky** [mongomock/mongomock#518]
In MongoDB, it is possible to test if array field contains some value by using following query: `{"array": "value"}`.

https://docs.mongodb.com/manual/reference/operator/query/eq/#array-element-equals-a-value

>**Array Element Equals a Value**
The following example queries the inventory collection to select all documents where the tags array contains an element with the value "B" [1]:
`db.inventory.find( { tags: { $eq: "B" } } )`
The query is equivalent to:
`db.inventory.find( { tags: "B" } )`
Both queries match the following documents:
`{ _id: 1, item: { name: "ab", code: "123" }, qty: 15, tags: [ "A", "B", "C" ] }`
`{ _id: 2, item: { name: "cd", code: "123" }, qty: 20, tags: [ "B" ] }`
`{ _id: 3, item: { name: "ij", code: "456" }, qty: 25, tags: [ "A", "B" ] }`
`{ _id: 4, item: { name: "xy", code: "456" }, qty: 30, tags: [ "B", "A" ] }`

So, the aforementioned query would match a document like `{"_id": 1, "array": ["value", "another value"]}`.

Docs don't explicitly state that `$ne` behaves similarly, but, in practice, I noticed that it does, and it would make sense since the operators are counterparts of each other.

https://docs.mongodb.com/manual/reference/operator/query/ne/

This issue has been previously reported in #323 and was closed, but I was able to reproduce it under mongomock 3.16.0, so maybe it's a regression?

Adding a piece of code to reproduce. Using regular `MongoClient` against a real database, these tests work, but with mongomock they fail.

```python
import mongomock


def test_eq_array():
    client = mongomock.MongoClient()
    collection = client.test_db.test_collection
    collection.insert_one({'_id': 1, 'array_field': [1]})
    query = {'array_field': {'$eq': 1}}  # {'array_field' : 1} would work similarly to explicit $eq
    matching_documents = collection.find(query)
    assert matching_documents[0]['_id'] == 1


def test_ne_array():
    client = mongomock.MongoClient()
    collection = client.test_db.test_collection
    collection.insert_one({'_id': 1, 'array_field': [1]})
    query = {'array_field': {'$ne': 1}}
    matching_documents = collection.find(query)
    assert list(matching_documents) == []
```

**Comment by pcorpet** [comment]
Thanks for reporting @NazarTopolsky and the very good examples. I'll take a stab at it.
