### ISSUE TITLE
aggregate function with '$out' parameter fails if no rows returned from $match stage

### ISSUE THREAD

**Issue by icohen88** [mongomock/mongomock#527]
aggregate function with '$out' parameter fails if no rows returned from $match stage

Assume we have an empty collection 'colc', and we run the next code:
```python
colc.aggregate([
		{'$match': {}},
		{'$out': 'out_colc'}
	])
```
So mongomock will raise the next exception:
```    raise TypeError('documents must be a non-empty list')
TypeError: documents must be a non-empty list
```

Although this is not the behavior in real mongo, which won't fail for that.

In order to fix that, need to check in `mongomock.aggregate._handle_out_stage` that `in_collection` is not empty, before using `insert_many`.

**Comment by pcorpet** [comment]
Thanks for the report.
