### ISSUE TITLE
$pull with $in fails in mock

### ISSUE THREAD

**Issue by ymoran00** [mongomock/mongomock#529]
I've tried the following:
`db.collection.update({}, {'$pull': {'arr': {'$in': ['a1']}}})`
This for a collection with documents in the form:
`{
        "b": 0,
        "arr": [
            "a1",
            "a2"
        ]
    }`
It's suppoed to the delete the 'a1' list item, but when using the mock I get:
`pymongo.errors.OperationFailure: unknown top level operator: $in`

**Comment by pcorpet** [comment]
Thanks for reporting. Actually the bug is not only for `$in` but any operator used in the condition. I'll create a fix.
