### ISSUE TITLE
No testable archive available

### ISSUE THREAD

**Issue by jayvdb** [mongomock/mongomock#530]
PyPI only has wheels, without tests.

When I attempt to use the GitHub tag archive tarballs, pbr complains that it isnt a versioned sdist:

```py
$ python setup.py build
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pbr/core.py", line 96, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/usr/lib/python3.7/site-packages/pbr/util.py", line 256, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/usr/lib/python3.7/site-packages/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/usr/lib/python3.7/site-packages/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/usr/lib/python3.7/site-packages/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/usr/lib/python3.7/site-packages/pbr/packaging.py", line 849, in get_version
    name=package_name))
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name mongomock was given, but was not able to be found.
error in setup command: Error parsing /tmp/4ia8nh44/mongomock-3.14.0/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name mongomock was given, but was not able to be found.
```

**Comment by pcorpet** [comment]
Hi @jayvdb, I'm not sure I understand the benefit of having tests inside the wheels. Can you tell me more or send me a pointer that explains it?

And for the versionning, I'm not sure how it's suposed to work https://github.com/mongomock/mongomock/blob/develop/mongomock/__version__.py

**Comment by jayvdb** [comment]
Tests shouldnt be in the wheels.  However I guess this can be solved by uploading sdist to PyPI.

**Comment by pcorpet** [comment]
@jayvdb please take a look at #534 and tell me if this would work for you.

**Comment by jayvdb** [comment]
The `MANIFEST.in` looks like it is a bit empty, and old.  Quite likely, if the sdist is run after the tests in CI, the sdist would include .pyc files because the `MANIFEST.in` says to include all of `tests`.

Maybe try PyPI `check-manifest` to see what other files it recommends you include in the sdist.

**Comment by pcorpet** [comment]
Good point. I've enhanced the `MANIFEST.in` file. Can you take another look (and answer in the PR) please?

**Comment by jayvdb** [comment]
Looks good.

**Comment by pcorpet** [comment]
OK, just need to wait for the next release (probably next week)
