### ISSUE TITLE
Sorting on DictField generates an error

### ISSUE THREAD

**Issue by LaundroMat** [mongomock/mongomock#531]
I have a Document containing a DictField:

    class Box(DynamicDocument):
        ...
        location = mongoengine.DictField(required=True)  
        ...
        meta = {
            'ordering': ['location']
        }

In production, calling e.g. `Box.objects.count()` works fine, but when testing and using pymongo, I'm getting this error:

    def _get_dataset(self, spec, sort, fields, as_class):
        dataset = self._iter_documents(spec)
        if sort:
            for sort_key, sort_direction in reversed(sort):
                if sort_key == '$natural':
                    if sort_direction < 0:
                        dataset = iter(reversed(list(dataset)))
                    continue
                dataset = iter(sorted(
                    dataset, key=lambda x: resolve_sort_key(sort_key, x),
                   reverse=sort_direction < 0))
                 
    E TypeError: '<' not supported between instances of 'dict' and 'dict'

Is this a bug in pymongo?

(FWIW, I fixed this by adding a class property that calculates a string based on the location dict. The queryset ordering is based on that property. I just wanted to mention this behaviour in case it's a bug).

**Comment by pcorpet** [comment]
Thanks for reporting, it's indeed a bug.
