### ISSUE TITLE
BulkWriteError doesn't correctly support ordered=False

### ISSUE THREAD

**Issue by danielcrisp** [mongomock/mongomock#533]
I'm working around mongoengine's lack of support for `insert_many` with `ordered=False` by doing this to get to the underlying pyMongo collection:

```python
doc_list = [doc.to_mongo() for doc in me_doc_list]

try:
    DocClass._get_collection().insert_many(doc_list, ordered=False)
except BulkWriteError as bwe:
    print(bwe.details)
```

However I'm getting unexpected results in my mongomock test. Essentially, if I try to insert multiple documents whose unique keys are already present in the mocked database I get a `BulkWriteError` but it only includes the details of the first document.

With `ordered=False` I'd expect to get `writeError` info for every duplicate document.

I wondered if by calling the protected `_get_collection()` method I'm somehow bypassing some essential part of the mocking?

I'll provide an example tomorrow.

**Comment by pcorpet** [comment]
Thanks for reporting @danielcrisp . Your example is good enough to find the bug. Actually it's because insert_many completely ignores the `ordered` parameter whereas the bulk writer does handle multiple write errors when called with `initialize_unordered_bulk_op`. I'll fix this (no need to provide an extra example).

**Comment by danielcrisp** [comment]
Wow - incredible. Thank you so much! 

Will this be available as version 3.16.1 on pip?

**Comment by pcorpet** [comment]
Not right away, I'll package one or two more changes and will release a 3.17

**Comment by danielcrisp** [comment]
Great, I look forward to it. Amazing work with the project and thank you for the very quick fix!
