### ISSUE TITLE
Collection.with_options only accepts kwargs

### ISSUE THREAD

**Issue by nathan-steyer** [mongomock/mongomock#537]
I have some code that calls `with_options` with the codec options as a positional arg
```python
options = CodecOptions(tz_aware=True)
modified_collection = collection.with_options(options)
```
which works for pymongo since the method definition lists out the supported kwargs, but not for mongomock since it doesn't. Minor, I know, but ideally it should work in mongomock

**Comment by pcorpet** [comment]
Hi @nathan-steyer , yes you're right we should try to have the same signature.

**Comment by pcorpet** [comment]
Note that specific codec options are not supported so your example code would trigger a `NotImplementedError` after my fix.
