### ISSUE TITLE
sort() with empty list works with mongomock but not with pymongo.

### ISSUE THREAD

**Issue by DusanMadar** [mongomock/mongomock#540]
`cursor.sort([])` does not raise `ValueError("key_or_list must not be the empty list")` with `mongomock` but it does with `pymongo`.

Tests with the code below pass with `mongomock`
```
mongo_client = mongomock.MongoClient()
sorting = []
cursor = mongo_client.db.collection.sort(sorting)
```

But with `pymongo` I have to do
```
mongo_client = mongomock.MongoClient()
cursor = mongo_client.db.collection
sorting = []
if sorting:
    cursor = cursor.sorting(sorting)
```

Versions:
Python 3.6.7
MongoDB 4.0.3
mongomock==3.16.0
pymongo==3.8.0

**Comment by pcorpet** [comment]
Good catch, thanks.
