### ISSUE TITLE
tz_aware-ness broken in 3.17

### ISSUE THREAD

**Issue by languitar** [mongomock/mongomock#542]
The `tz_aware` flag is not passed correctly from the `MongoClient` constructor to the `codec_options`. This worked before:

```
In [7]: mongomock.MongoClient(tz_aware=True).codec_options.tz_aware                                                                                                                                                 
Out[7]: False
```

**Comment by pcorpet** [comment]
Note that it never worked properly: before 14a87ee5, MongoClient did not have any `codec_options` so it would actually return a `Database` called `codec_options` and then `tz_aware` would return a collection in this table. However we should not fail silently like this.

**Comment by languitar** [comment]
Right,  I also noticed that after reporting the issue, but still the change effectively broke some tests in my case.
