### ISSUE TITLE
README demo TypeError

### ISSUE THREAD

**Issue by M0roSan** [mongomock/mongomock#545]
In demo option 3, it returns TypeError: 'NoneType' object is not subscriptable.
find_one returns None object because `obj['_id'] = collection.insert_one(obj)` returns object. 

quick fix is to make `obj['_id'] = collection.insert_one(obj).inserted_id` instead

**Comment by pcorpet** [comment]
@MasahiroYoshida thanks for the catch. Fixing it ASAP.
