### ISSUE TITLE
Aggregation operator '$first' raise `IndexError` if `values` is empty

### ISSUE THREAD

**Issue by icohen88** [mongomock/mongomock#546]
When using the aggregation operator `$first` (or `$last`), and no data exists in the group, we will get `IndexError` exception.

Suggestion for a fix:
In `aggregate._accumulate_group`, instead of:
```
            elif operator == '$first':
                doc_dict[field] = values[0]
            elif operator == '$last':
                doc_dict[field] = values[-1]
```
do
```
            elif operator == '$first':
                doc_dict[field] = values[:1]
            elif operator == '$last':
                doc_dict[field] = values[-1:]
```

**Comment by icohen88** [comment]
After a second thought, my suggestion is not good because then `doc_dict[field]` will be a list. So another option could be to use try-catch.

**Comment by pcorpet** [comment]
Hi, thanks for reporting. I'll send a fix ASAP.
