### ISSUE TITLE
Incorrect pymongo version requirements

### ISSUE THREAD

**Issue by macdjord** [mongomock/mongomock#552]
MongoMock 3.17.0 is incompatible with PyMongo 3.6.1, but this dependency is not declared in `pip`

# Steps to Reproduce:
```bash
echo > requirements.txt <<HERE
mongomock == 3.17.0
pymongo == 3.6.1
HERE
pip install -r requirements.txt
```

# Expected result:
* `pip` warns of incompatible version requirements

# Actual results:
* No warning is emitted
* MongoMock fails, IIRC, on setting up the connection

# Suggested fix:
* Configure MongoMock's test suite to use a specific PyMongo version
* Declare `pip` a dependency on `pymongo >= $FOO` where `$FOO` is the version used for testing
* If MongoMock needs to upgrade to a newer PyMongo version to take advantage of newer features, increment both the test suite and `pip` version requirements

**Comment by pcorpet** [comment]
Hi @macdjord, thanks for reporting.

Note that `mongomock` is supposed to work without `pymongo`. We even have test suites checking that. So I think your solution wouldn't work. However we should not crash if the version of `pymongo` is too low: we should fallback to make it work as if `pymongo` was not there. And maybe update the error messages for the features where `pymongo` is required.

I'd be interested in getting the exact error message, otherwise I'll try to reproduce when I'm back on a better network.

**Comment by macdjord** [comment]
The error:
```
tests\foo\bar\test_somthing.py:74: in test_stuff
    my_doc.save(force_insert=True)
[REDACTED]\lib\site-packages\mongoengine\document.py:382: in save
    object_id = self._save_create(doc, force_insert, write_concern)
[REDACTED]\lib\site-packages\mongoengine\document.py:434: in _save_create
    with set_write_concern(collection, write_concern) as wc_collection:
[REDACTED]\lib\contextlib.py:82: in __enter__
    return next(self.gen)
[REDACTED]\lib\site-packages\mongoengine\context_managers.py:247: in set_write_concern
    yield collection.with_options(write_concern=WriteConcern(**combined_concerns))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = Collection(Database(mongomock.MongoClient('localhost', 27017), 'monogoenginetest'), 'user')
codec_options = None, read_preference = None, write_concern = WriteConcern(w=1)
read_concern = None

    def with_options(
            self, codec_options=None, read_preference=None, write_concern=None, read_concern=None):
        for key, options in iteritems(_WITH_OPTIONS_KWARGS):
            value = locals()[key]
            if value is None:
                continue
            for attr in options.attrs:
                if not hasattr(value, attr):
                    raise TypeError(
>                       '{} must be an instance of {}'.format(key, options.typename))
E                   TypeError: write_concern must be an instance of pymongo.write_concern.WriteConcern
```

**Comment by swesterveld** [comment]
I can confirm this issue, as I ran into it some days ago in a project I'm working on.

I've prepared this repository with a simplified version of this project: https://github.com/swesterveld/mongo_engine_mock

It has 2 branches:
* `master`: with `pymongo==3.6.1` specified in the Pipfile
* `pymongo-3-7-0`: with `pymongo==3.7.0` specified in the Pipfile

When running `pipenv run pytest test.py`:
* on `master` it fails
* on `pymongo-3-7-0` it passes

**Comment by pcorpet** [comment]
I'm a bit too strict when checking that we're getting a WriteConcern object: I'm ensuring that there is a `is_server_default` which is not the case in pymongo 3.6.1.

**Comment by macdjord** [comment]
That fixes the immediate cause of this issue, but the underlying problem still remains: MongoMock will use versions of PyMongo which it has never been tested with.

How about this:

- Reconfigure the test suite so that it runs twice: once with pymongo-3.7.0, and then again with no pymongo at all
- Change the 'Is pymongo installed?' test so that it ignores any version of pymongo lower than 3.7.0 and uses the fallback just as it would if pymongo were not installed in the first place

**Comment by pcorpet** [comment]
> Reconfigure the test suite so that it runs twice: once with pymongo-3.7.0, and then again with no pymongo at all

This is already the case

> Change the 'Is pymongo installed?' test so that it ignores any version of pymongo lower than 3.7.0 and uses the fallback just as it would if pymongo were not installed in the first place

I'd rather run tests with an old version of pymongo to make sure we support it. I'll do that with pymongo 3.6.1 for now, and lower the bar if someone asks me.
