### ISSUE TITLE
Errors not generated on invalid query operators or operands

### ISSUE THREAD

**Issue by macdjord** [mongomock/mongomock#553]
MongoMock does not raise an error if a query uses an invalid operator or operand like the real MongoDB does

# Steps to Reproduce:
* `find({'some_field': {'$foo': 'bar'}})`
* `find({'some_field': {'$in': 'not a list'}})`

# Expected result:
* Both operations fail, the first because there is no '$foo' operator and the second because '$in' takes a list, not a single value
  * This is, in fact, what the real MongoDB does on receiving those queries

# Actual results:
* Both operations run successfully, returning 0 results

**Comment by pcorpet** [comment]
Woops, thanks for catching. Note that those are two different issues.
