### ISSUE TITLE
drop_database not removing stored data

### ISSUE THREAD

**Issue by anon4777** [mongomock/mongomock#565]
Drop_database method is not removing stored data in some cases, see example below:

    import mongoengine
    from mongoengine import Document, StringField

    ALIAS = "alias"

    class Content(Document):

        slug = StringField(required=True)

        meta = {'allow_inheritance': True,
                'db_alias': ALIAS}

    class Foo(Content):

        pass

    database = mongoengine.connect(ALIAS, host="mongomock://localhost")
    mongoengine.register_connection(alias=ALIAS, host="mongomock://localhost")

    foo1 = Foo(slug="slug1")
    foo1.save()
    foo2 = Foo(slug="slug2")
    foo2.save()

    print(Foo.objects.all(), "result before drop")

    database.drop_database(ALIAS)

    print(Foo.objects.all(), "result after drop")

Output:

    [<Foo: Foo object>, <Foo: Foo object>] result before drop
    [<Foo: Foo object>, <Foo: Foo object>] result after drop

Tested with mongomock 3.17.0.

**Comment by pcorpet** [comment]
Thanks for reporting and for the example.

It seems that you've created two connection to the same server and that you're adding objects using one, and deleting them using the second. However the basic mode of mongomock is not to create a server but to mock the whole server from within a connection. That makes it quite easy to create isolated tests: when you create a new test, with a new connection, all the data from the previous tests are gone. This also means that two connections to the same server, are actually mocked by two mock servers.

To have the behavior you're expected, you should be using the `mongomock.patch` interface that creates an environment where multiple connexion to the same server access and modify the same data. However, I think that it would require changes in `mongoengine`, so maybe you should create an issue on that repo.

**Comment by anon4777** [comment]
Thank you for the reply.
 
I am using pytest with a function-scope fixture and could not understand why the data were persistent among multiple test functions. Now I see that I was in fact using two separate connections, as you said. Therefore, I removed the lines mentioning the database

    database = mongoengine.connect... 

    database.drop_database...

and I use 

    db = mongoengine.get_db(alias)
    mongoengine.get_connection(alias).drop_database(db)

as a tear-down instead and everything is working fine now.

Thank you again for your help.
