### ISSUE TITLE
Creating index with custom name !!

### ISSUE THREAD

**Issue by sachinavina** [mongomock/mongomock#566]
In latest Mongo(4.2)/pymongo(3.9.0), supports creating index by providing custom name but in mongomock this is not supported yet.

**Comment by pcorpet** [comment]
It's actually supported by pymongo for a long while, not a recent feature.

**Comment by pcorpet** [comment]
It was actually implemented by @rbu in #550. It might be time for a new release.

**Comment by rbu** [comment]
:champagne: @pcorpet, thanks for pushing out a new release!

(reference: this feature got released in 3.18.0 today).
