### ISSUE TITLE
MongoMock changes inserted datetime in inserted documents?

### ISSUE THREAD

**Issue by jschlyter** [mongomock/mongomock#573]
I'm experiencing problems with MongoMock (3.18.0) changing data upon insertion, something that does not occur when using PyMongo. If the document contains a datetime with timezone, the datatime is converted to UTC and the timezone dropped. Fetching the document again brings back the timezone.

Example code to trigger error:

```
from datetime import datetime, timezone, timedelta
import pymongo
import mongomock

def test_with_client(client):
    doc = {
        'dt': datetime.now(tz=timezone(timedelta(hours=2)))
    }
    print("Before save:  ", doc['dt'])
    res = client.test.broken.insert_one(doc)
    print("After save:   ", doc['dt'])

    res = client.test.broken.find_one({'_id': res.inserted_id})
    print("After get:    ", res['dt'])

print("Test with MongoDB")
test_with_client(pymongo.MongoClient(tz_aware=True))
print("")

print("Test with MongoMock")
test_with_client(mongomock.MongoClient(tz_aware=True))
print("")

```

Outputs:

```
Test with MongoDB
Before save:   2019-10-18 13:27:08.209182+02:00
After save:    2019-10-18 13:27:08.209182+02:00
After get:     2019-10-18 11:27:08.209000+00:00

Test with MongoMock
Before save:   2019-10-18 13:27:08.215341+02:00
After save:    2019-10-18 11:27:08.215000
After get:     2019-10-18 11:27:08.215000+00:00
````

Perhaps related to #410.

**Comment by jschlyter** [comment]
It seems https://github.com/mongomock/mongomock/blob/develop/mongomock/collection.py#L476 is the culprit. Perhaps it would be better if `_insert` would copy the data before altering it? Or if `patch_datetime_awareness_in_document()` could not clear the TZ if we are tz_aware?

**Comment by pcorpet** [comment]
Yeah, I totally agree. I hate that mongomock is modifying the objects that it's given. Let me prioritize that fix.

**Comment by pcorpet** [comment]
Hmmf, apparently `pymongo` does modify the input (but only to add the _id).
