### ISSUE TITLE
Request for release of new version

### ISSUE THREAD

**Issue by oudingfan** [mongomock/mongomock#591]
I'm using Python3.8, and can't work well without https://github.com/mongomock/mongomock/commit/7fc6ae4dc991cbdf73596bfb278d8cb0092ee1a5.
So I wish a new version could be released.
I appreciate for your work, thank you.

**Comment by pcorpet** [comment]
Done. Enjoy :-) https://github.com/mongomock/mongomock/releases/tag/3.19.0

**Comment by oudingfan** [comment]
Thank you very much!
