### ISSUE TITLE
inserting a bson.Timestamp(0, 0) not setting it to current date

### ISSUE THREAD

**Issue by languitar** [mongomock/mongomock#592]
In MongoDB, inserting a `bson.Timestamp(0, 0)` results in a document where this timestamp is set to the current date with increment 1:

```
(Pdb) import bson
(Pdb) collection.insert_one({'x': bson.Timestamp(0, 0)})
<pymongo.results.InsertOneResult object at 0x7f58991af2c0>
(Pdb) collection.find_one({'x': {'$exists': True}})
{'_id': ObjectId('5e43e9d9fb5c6747e957f8e1'), 'x': Timestamp(1581509081, 1)}
```

mongomock does not implement this behavior and the Timestamp remains at 0, 0.

**Comment by pcorpet** [comment]
@languitar thanks for reporting. Please review my PR.

**Comment by languitar** [comment]
Thanks for the very quick fix!
