### ISSUE TITLE
[BUG] Cannot compare UUID fields

### ISSUE THREAD

**Issue by voegtlel** [mongomock/mongomock#609]
### Error description
I'm getting
```
NotImplementedError: Mongomock does not know how to sort 'c4be03d6-6e0f-42ef-a043-d35b269692ec' of type '<class 'uuid.UUID'>'
```
when trying to run (minimal example):
```Python
from mongomock import MongoClient
from uuid import UUID

coll1 = MongoClient()['db'].coll1
coll1.insert_one({'_id': UUID(int=1)})
coll1.find({}, sort=[('_id', 1)])
```

### Probable solution
Probably, that's caused by https://github.com/mongomock/mongomock/blob/50ad34e438d2d12e4ccb2926fba1a76d508fd052/mongomock/filtering.py#L322-L352
missing `UUID` as a type. My guess from here: https://github.com/mongodb/mongo/blob/f10f21467c2c0ae7586c5c9d327f2328f09d655c/src/mongo/bson/bsontypes.h#L175 is that it could suffice to replace:
```Python
if isinstance(val, (bytes, UUID)):
    return 30
```
?

### Why?
To illustrate, why this makes sense: When using `timestamp` (with higher precision that `ObjectID`) to make sure, objects with the same timestamp are deterministically ordered:
```Python
from mongomock import MongoClient
from uuid import UUID

coll1 = MongoClient()['db'].coll1
coll1.insert_many([
  {'_id': UUID(int=3), 'timestamp': 99},
  {'_id': UUID(int=1), 'timestamp': 100},
  {'_id': UUID(int=2), 'timestamp': 100},
])
coll1.find({}, sort=[('timestamp', 1), ('_id', 1)])
```

Thank you!

**Comment by Kalbi** [comment]
Bumping this because I'm also running into this, except i'm trying to use `aggregate` and passing a UUID field into `$group`, which is mentioned in this long open issue: https://github.com/mongomock/mongomock/issues/576

It seems that @voegtlel makes a good point:
> missing UUID as a type. My guess from here: https://github.com/mongodb/mongo/blob/f10f21467c2c0ae7586c5c9d327f2328f09d655c/src/mongo/bson/bsontypes.h#L175 is that it could suffice to replace...

Is there a reason the above proposed solution wouldn't work/be fairly simple to implement?

**Comment by pcorpet** [comment]
Let's try a simple PR and check if it passes the tests.
