### ISSUE TITLE
Doesnt patch the alias import of pymongo.MongoClient

### ISSUE THREAD

**Issue by coolkp** [mongomock/mongomock#613]
When i import 
from pymongo import MongoClient as client 
the decorator patching @mongomock.patch(servers=(('127.0.0.1', 27017),)) does not work. 
for client('127.0.0.1'). 
Only pymongo.MongoClient('127.0.0.1') works

**Comment by pcorpet** [comment]
yes, unfortunately patching isn't easy and once you have imported the `MongoClient` you already hold the real class which makes it hard to change it to the mocked one.
