### ISSUE TITLE
DocumentTooLarge not implemented

### ISSUE THREAD

**Issue by cbensimon** [mongomock/mongomock#622]
I have been testing an app with mongomock and the project is really cool, thank you !

However I ran a real MongoDB server and encountered a `DocumentTooLarge` error that wasn't here with mongomock

I have been searching for "DocumentTooLarge" in the issues and in the source code but I didn't find anything, so I suppose it has not been implemented
Would it be relevant to do so ?

Thank you,
Charles

**Comment by pcorpet** [comment]
Yes totally, feel free to give it a try. I'm OK if we don't have the exact same limit as pymongo, but it would be nice to have kind of the same.

**Comment by duarte-pompeu** [comment]
Would be interesting to have this!
