### ISSUE TITLE
Add '$switch' in the aggregate pipeline

### ISSUE THREAD

**Issue by haripriyan** [mongomock/mongomock#631]
When executing aggregate functions via MongoEngine making use of the aggregation pipeline operation of `$switch`, mongomock raise an `pymongo.errors.OperationFailure: Unrecognized expression '$switch'` exception.

Example
```
pipeline = [{'$group': {'_id': {'$switch': {'branches': [
            {'case': {'$gte': ['$COLUMN_VALUE', 50]}, 'then': 'HIGH'},
            {'case': {'$gte': ['$COLUMN_VALUE, 30]}, 'then': 'MEDIUM'}
        ],
            'default': 'LOW'
        }},
      "totalSum": {'$sum': "$AMOUNT"}}}]

MongoObjectModel.objects.all().aggregate(pipeline)
```

**Comment by pcorpet** [comment]
It's a bug to raise an `OperationFailure` as it should raise a `NotImplmentedError`. However I think the real solution for you would be the implementation of the feature itself in mongomock.
