### ISSUE TITLE
[Question] Clarify the limitation of mongomock.patch

### ISSUE THREAD

**Issue by dayfine** [mongomock/mongomock#632]
Hi I was trying to use `@mongomock.patch` but couldn't get it to work. The situation is that I am using the [mongodbio](https://github.com/apache/beam/blob/master/sdks/python/apache_beam/io/mongodbio.py) connector for Beam. It is this function that internally creates a mongodb connection. I can specify the uri it should use and patch that uri, but internally it cannot connect to that address, e.g. `pymongo.errors.ServerSelectionTimeoutError: fakehost.com:27017: timed out`. If I use `localhost`, then data will actually be written to the local database.

This made me think `@mongomock.patch` isn't working here, and I wonder if the reason is because the code creating the client (e.g. beam code calling pymongo.MongoClient) is not within the scope of my test and module, and there is no way to inject it.

**Comment by r0x0d** [comment]
I'm having the same problem as you, except that it's an inner class for a project I created, but the idea is similar. This class will return a new connection with mongodb via PyMongo, however, I can't use the patch to simulate a connection mock through it.

Any of the maintainers can help us? @pcorpet

**Comment by pcorpet** [comment]
HI @dayfine the trouble is that `mongodbio` gets the `MongoClient` object before it gets patched (see [here](https://github.com/apache/beam/blob/master/sdks/python/apache_beam/io/mongodbio.py#L84). Therefore you would need to patch before any import of `mongodbio`.

@nicht, if it's in your won code I recommend using `MongoClient` like this:

```py
import pymongo

....
pymongo.MongoClient(...)
```

(instead of `from pymongo import MongoClient`).

I'll update the documentation of the patcher.

**Comment by dayfine** [comment]
It sort of makes sense, but I am not sure what exactly to do. I've tried something like:
```
class BeamMongoUtilTest(TestCase):

    @mongomock.patch()
    def test_beam_mongodb_write_and_read(self):
        # mongo_util modules imports mongodbio
        from my_module import mongo_util
        ...
		test things
```
But this still connects the real db.

**Comment by pcorpet** [comment]
Would it be possible that your test module already imports (directly or indirectly) the `mongodbio` module? if so, then it's cached.
