### ISSUE TITLE
PyMongo 2.9.5 + mongoengine incompability - unexpected keyword argument 'snapshot'

### ISSUE THREAD

**Issue by juannyG** [mongomock/mongomock#638]
When running most mongomock versions against most `pymongo==2.9.5` + `mongoengine>=0.10.6` version, the following error is thrown:

```    @property
    def _cursor(self):
        """Return a PyMongo cursor object corresponding to this queryset."""
    
        # If _cursor_obj already exists, return it immediately.
        if self._cursor_obj is not None:
            return self._cursor_obj
    
        # Create a new PyMongo cursor.
        # XXX In PyMongo 3+, we define the read preference on a collection
        # level, not a cursor level. Thus, we need to get a cloned collection
        # object using `with_options` first.
        if IS_PYMONGO_3 and self._read_preference is not None:
            self._cursor_obj = self._collection\
                .with_options(read_preference=self._read_preference)\
                .find(self._query, **self._cursor_args)
        else:
            self._cursor_obj = self._collection.find(self._query,
>                                                    **self._cursor_args)
E           TypeError: find() got an unexpected keyword argument 'snapshot'

/usr/local/lib/python2.7/site-packages/mongoengine/queryset/base.py:1569: TypeError
```
This occurs with `mongoengine` versions from 0.10.6 all the way through 0.15.3 - maybe more but I was unable to test further version pairings.

Cause:
When [mongonengine is generating the cursor args](https://github.com/MongoEngine/mongoengine/blob/v0.15.3/mongoengine/queryset/base.py#L1518-L1548), it adds the `snapshot` argument, which is [not defined in the mongomock's Collection.find method](https://github.com/mongomock/mongomock/blob/develop/mongomock/collection.py#L976-L980) - thus generating a `TypeError`. 

It seems mongoengine is trying to juggle the pymongo<3 scenario, but that doesn't fit the expectations in mongomock.

Is this expected behavior? Is pymongo<3 not supported by this library?

**Comment by pcorpet** [comment]
Yes, in general we do not support older versions of pymongo for very long. However if you don't need the snapshot feature but merely the keyword arg I can definitively add it. It will raise a `NotImplementedError` if it's used with `True` though.

**Comment by pcorpet** [comment]
Actually pymongo + MongoDB returns an OperationFailure (and not a TypeError) error when snapshot is not False, so I'm updating the code to reflect that. However I won't extend the compatibility to PyMongo 2.9.5, sorry.

**Comment by juannyG** [comment]
Thank you for the response @pcorpet.

This was more to understand general version support, as I couldn't find anywhere in the README/docs an explicit pairing of supported versions of pymongo <---> mongoengine <---> mongomock

Feel free to close this issue at your discretion.
