### ISSUE TITLE
GridFS: TypeError: database must be an instance of Database

### ISSUE THREAD

**Issue by anatoly-kor** [mongomock/mongomock#639]
Hi. I found some closed issues (#111, #526, #72). I have the same bug. 
My thoughts: It looks like what bug in differences **pymongo.database.Database** and **mongomock.Database**. That's the reason for `TypeError: database must be an instance of Database` for GridFS.

```python
import mongomock
import pymongo

db = pymongo.MongoClient().db_example

print(isinstance(db, pymongo.database.Database))  # True
print(isinstance(db, mongomock.Database))    # False
```

The same error with **Collections**. If just comment lines of code with the checking instance in source code of GridFS all tests passed and no errors.

**Comment by pcorpet** [comment]
This is the reason we have `mongomock.gridfs.enable_gridfs_integration()` make sure you call it before using gridfs on a Mongomock instance.

Please reopen if it doesn't work for you or if you have an idea on documenting it better.
