### ISSUE TITLE
Support for '$regexMatch'

### ISSUE THREAD

**Issue by gwainer** [mongomock/mongomock#647]
Hello, Using MongoMock version `3.19.0`, I was testing aggregation using new `$regexMatch` operator from mongoDB version `4.2`. Here are the docs: https://docs.mongodb.com/manual/reference/operator/aggregation/regexMatch/ .

It seems it's not supported yet. The following error arises when running the test:

```
  File "/Users/gcw/.pyenv/versions/3.7.6/envs/tqtq-api-env/lib/python3.7/site-packages/mongomock/aggregate.py", line 189, in parse
    raise OperationFailure("Unrecognized expression '%s'" % k)
pymongo.errors.OperationFailure: Unrecognized expression '$regexMatch'
```

This would be a feature request. Thanks.

**Comment by pcorpet** [comment]
yes new features are not always reported properly. I've just fixed it for next version: it should raise a `NotImplementedError`. Feel free to contribute to implement the actual feature.

**Comment by pcorpet** [comment]
@gwainer please review #658. I'll wait for your "go" before I merge it.
