### ISSUE TITLE
mongomock is not compatible with pymongo 3.11.0

### ISSUE THREAD

**Issue by kosqx** [mongomock/mongomock#648]
The [just released](https://pypi.org/project/pymongo/#history) pymongo 3.11.0 introduced the `hint` parameter to the following methods:

- `add_update()`
- `add_replace()`
- `add_delete()`

This is causing the exceptions similar to:

```
TypeError: add_update() got an unexpected keyword argument 'hint'
```

**Comment by pcorpet** [comment]
Yes, major bug. Thanks for finding it so quickly.
