### ISSUE TITLE
Support the `aggregate` method for collections

### ISSUE THREAD

**Issue by ymost** [mongomock/mongomock#65]
http://docs.mongodb.org/manual/reference/method/db.collection.aggregate/

**Comment by GabrielBlondeau-Kirby** [comment]
Hi guys,

Three years later ^^, but mongomock don't support `aggregate` right ?

**Comment by smalekzadeh** [comment]
Hi
I get "'Collection' object is not callable" when trying to test aggregate pipeline. Example

aggresults = mongocdr.aggregate(pipeline)

The code works with the mongodb client but produces the above error when using mogomock in unit tests. can anyone help please?

Thanks

**Comment by pcorpet** [comment]
Aggregation method is now working pretty well in recent versions of mongomock. Not all operations are available yet, but I think we can close this issue.
