### ISSUE TITLE
Falsy values in mongomock are different than in MongoDB

### ISSUE THREAD

**Issue by kosqx** [mongomock/mongomock#650]
In MongoDB only the following values are falsy (the values that are considered false when encountered in a boolean context):

- `false`
- `null`
- `0`
- `undefined`

The official documentation points to [this description](https://docs.mongodb.com/manual/reference/operator/aggregation/and/#and-boolean-behavior):

> In addition to the `false` boolean value, $and evaluates as false the following: `null`, `0`, and `undefined` values. The $and evaluates all other values as true, including non-zero numeric values and arrays.

The Python (and in result also `mongomock`) have much longer list of falsy values. To name a few:

- `""` (empty string)
- `[]` (empty list)
- `{}` (empty dict)

Adding of the following test to the `tests/test__mongomock.py` will demonstrate the bug:

```py
    def test__aggregate_cond__falsy(self):
        self.cmp.compare_ignore_order.aggregate([
            {'$project': {
                'new_value': {'$cond': ['', 2, 3]},  # <-- only important line, notice the empty string
            }},
        ])
```

Right now this affects (probably only) `$cond` but in future will affect also `$switch`, `$anyElementTrue`, `$allElementsTrue`, `$and`, `$or`, `$not`.

**Comment by pcorpet** [comment]
You're totally right. Do you want to take on this bug?
