### ISSUE TITLE
TTL index support - high level proposal

### ISSUE THREAD

**Issue by juannyG** [mongomock/mongomock#655]
While using 
* mongomock==3.19.0
* mongonengine==0.20.0
* pymongo==3.10.1

I ran into an issue that appears with `update` that was resolved in https://github.com/mongomock/mongomock/pull/628

Sadly (for me) this was released in version 3.20.0 along side [a commit that raises a `NotImplementedError` when it sees TTL indexes](https://github.com/mongomock/mongomock/commit/cd034305d03534223db4b04d18252280fc29855e#diff-4901d650fcdfbe042f25fcaf722eb2cc) that makes my test suite explode with exceptions at this line when trying to upgrade from 3.19.0 to 3.20.0.

I see that [expiring data is listed in one of the missing features](
https://github.com/mongomock/mongomock/blob/develop/Missing_Features.rst) and before I went ahead and implemented anything, I thought it prudent to ask first if there were any considerations/gotchas/preferences of implementation - I haven't seen anything in the issues list, however.

I think the expiry feature could (should) be done in a two prong approach: 
1. [one for the TTL index ](https://docs.mongodb.com/manual/tutorial/expire-data/#expire-documents-after-a-specified-number-of-seconds)
2. [another for the specific clock time expiry](https://docs.mongodb.com/manual/tutorial/expire-data/#expire-documents-after-a-specified-number-of-seconds)

While (1) is being implemented, a similar `NotImplemented` approach could be used for (2) (i.e. if we see `expireAt` - sorry, `raise NotImplementedError`)

My initial reaction to solve (1): 
* adding a sort of specialization to the collections store of indexes to track `expireAfterSeconds` - I think this might be the easier part...
* when a document is first created, an extra hidden property is added to the "record", of "now + expiry" datetime, indicating when the record would/should be "deleted" - this feels a little trickier, mostly because I haven't dug into this area of the library (yet...:smile: )

The final piece of the puzzle lies in "OK - you've expired - get out." Per the mongo documentation:

> _The TTL feature relies on a background thread in mongod that reads the date-typed values in the index and removes expired documents from the collection._

Well - we don't have that - we're locked in the GIL (I wouldn't recommend async for this either). At some point during collection and/or document access, some kind of examination of the collection could occur, effectively executing the responsibility of the `mongod` background thread, and remove the expired records.

That last piece would certainly benefit from some performance analysis. But before that, circling back to my original stated intent - I'd love any feedback (even if it's a simple "Yep - if you can make this happen - you're a go" or "We've thought about that and it's not possible") on this approach.

**Comment by pcorpet** [comment]
Thanks for asking first and sorry for the trouble the update caused you.

I think a more pragmatic approach could be a way to specify somehow to mongomock that you understand that TTL is not implemented and that you're OK with that in your tests (easy fix for you). That could be a more general framework where one would be able to silent many NotImplementedError while testing other features.

However, this could be an occasion to get TTL in mongomock! So let's answer your proposal:
> While (1) is being implemented, a similar NotImplemented approach could be used for (2) (i.e. if we see expireAt - sorry, raise NotImplementedError)

I'm totally in line with you on that, don't hesitate to stop your implementation at any time and raise a NotImplementedError if you can split the feature.

> adding a sort of specialization to the collections store of indexes to track expireAfterSeconds - I think this might be the easier part...

This one should actually be stored in the index dict itself, as the `list_indexes` is supposed to return it. So yes this will be easy.

> an extra hidden property is added to the "record", of "now + expiry" datetime

I don't see why you need that. As far as I understand the feature does not base the deletion on `now` but on the value's field. So if you store a document, you already have the field's value and the document should be deleted at `field_value + expiry` datetime. As such you don't need to store any new field (BTW if you do that you'll need to be extra careful on what you return).

So in fine, you would only need the process to check the expiration when accessing the document and you could, at that time, check the field's value and read the expireAfterSeconds value before making a call.

Note that you'll also need a central place in mongomock to handle "Mongomock's time", so that testers can easily play with time and fast-forward in the future to test what happens then.

**Comment by juannyG** [comment]
Thank you so much for your response!

With regards to the more pragmatic approach: that's actually a really great idea for the short term...a kind of `MONGOMOCK_TTL_OK` flag or something...another configuration/flag could also be used for `expireAt` indexes - to your point "a more general framework" which would add more controls for testers. In a sense, I'm thinking of it effectively being a "feature flag" - but it could be more generally get into "mongomock configs."

I definitely wouldn't mind playing around with that as it might help me get more familiar with the internals of the framework. However, I can see that also expanding in complexity as I believe it quickly starts to brush up against the concepts of "How and where do `mongomock` configs live? how are they accessed? initialized?" A bit of a different "question/problem" space than I had originally anticipated and/or thought through 😄 

As for my ` "now + expiry" ` reference - you're absolutely right! You can tell I've been using TTL indexes specifically on `created` fields that default to `now` 😉 😉 

I'm not sure I follow with respect to "Mongomock's time" - if expiration is dictated relative to the field value + expiry, wouldn't testers simply manipulate the particular field? Or is it more from the point of view of - depending on implementation, if removal occurs during access, how would one update the field if the document was removed...because you're accessing it....and I'm removing it? _engage infinite loop spiral_

Great feedback - lots to think about - and thanks again for the wonderful framework. I look forward to your response, but in the mean time - I'll probably start playing around with some of this :-)

**Comment by pcorpet** [comment]
For the ignoring framework, please review #656.

> I'm not sure I follow with respect to "Mongomock's time" 

Typically I would expect a user of `mongomock` to do:

1. create a collection
2. create an index with a TLL of 1h
3. insert some documents at NOW or at another given time
4. fake waiting 1h and a half
5. list the documents and realize that the ones that the correct ones are gone

As you can see the item 4 is quite problematic: either you need your test to wait for 1h and half before checking, or reduce the expire time of your index (which you might not always able to do), or be able to manipulate on which time mongomock bases its decision.

**Comment by juannyG** [comment]
RE: ignoring framework - makes sense. I had thought of a similar "function-state-tracking" approach, but wasn't sure if you might want some kind of "settings object" similar to Django or Django Rest Framework.


For "Monogmock time" - ahhh, ok - if that's an expected use case, I see what you mean now.

However, I feel as though that would be an additive feature. My reasoning here is - if I create a document and set the field value to 2 hours in the past, but the collection has a 1 hour expiry...if I try to retrieve it - it should no longer exist. No fake-waiting or expire time reduction needed in that use case.

I guess the question becomes - should the framework provide a "time-manipulation" feature - or is it on the user to set the field values accordingly per the expectations of their test?

If this is something you feel strongly should be included with the TTL index, I could provide a context manager that would take in the desired "time delta" to wind the clock up, which could then be used to in the document access discussed previously - `field_value + expiry + time_wind`. Hope this high level/rough sketch on that "time manager" helps.

**Comment by pcorpet** [comment]
For the ignoring framework, please review deeply it to hunt for bugs and add a comment with "LGTM" to the reviewing thread when you think I can push to the main branch.

Yep, I think your usecase would be covered without mocking time and would be enough to do some of the testing.

For mocking the time, I'd rather use a typical mocking pattern where `mongomock` uses a central function to get the current time, and users only need to mock that call.

For now we do it in various forms:
- `time.time()`
- `datetime.utcnow()`
and those forms are using builtins which makes the whole thing hard to mock.

For me the basic usage should look like:
```py
@mock.patch('mongomock.utcnow')
def test_ttl(self, mock_utcnow):
  mock_utcnow.return_value = datetime.datetime.utcnow()
  ... do some stuff ...
  mock_utcnow.return_value = datetime.datetime.utcnow() + datetime.timedelta(hours=1.5)
```

So no need to create a dedicated context manager but let's make sure we are consistant across the whole mongomock code when we access "current" time.

**Comment by juannyG** [comment]
👍 👍 👍  - makes total sense

I'm currently working on ironing some issues on my local to get tox running (and _passing_) properly - most things work/pass - but I'm seeing odd errors here & there - definitely local configuration issues...but I'll get into the ignoring framework PR in the next few days.

Thanks again for all your input!!
