### ISSUE TITLE
Sum returns incorrect value

### ISSUE THREAD

**Issue by victorct-pronto** [mongomock/mongomock#657]
It seems to be `sum`  is returning the wrong value, I have the following schema:

```
class Order(Document):
      created_at = DateTimeField()
      subtotal = DecimalField()
```

When I execute the following code:

```
now = datetime.datetime.now()
Order(subtotal=100, created_at=now).save()
Order(subtotal=400, created_at=now).save()

orders = Order.objects(created_at=now) # returns an array of 2 orders
sum_total = orders.sum("subtotal")
another_sum_total = sum(map(lambda o: o.subtotal, orders))

print(sum_total) # It prints 0
print(another_sum_total) # It prints 500 which is correct
```

Here are some screenshots from my test suite:

![image](https://user-images.githubusercontent.com/56981448/90176066-0b109a80-dd6e-11ea-8b77-52fb6aacf2b3.png)

![image](https://user-images.githubusercontent.com/56981448/90176106-15cb2f80-dd6e-11ea-80ca-1b05fb372644.png)

**Comment by pcorpet** [comment]
Hi @victorct-pronto , this is Mongomock, not mongoengine. I would appreciate if you could update the bug in a sense that made sense to those of us that are not mongoengine users. Thanks.

**Comment by victorct** [comment]
@pcorpet of course I will do that first thing in the morning :)

**Comment by pcorpet** [comment]
Which morning? :-P

I've tried to reproduce, but I still don't understand how it works with mongoengine + mongo DB (without mongomock), so it's hard to replicate with mongomock.
