### ISSUE TITLE
[Feature Request] Implement CodecOptions

### ISSUE THREAD

**Issue by hellocoldworld** [mongomock/mongomock#662]
Is it desriable to implement codec_options kwarg to `Database.get_collection` call?

**Comment by pcorpet** [comment]
Yes it is, I've been starting something around this but it's a bigger piece of work than what I originally thought.

What codec option would you like to use?

**Comment by pcorpet** [comment]
@hellocoldworld would you take a look at #670 please? I'll welcome any details of code review that you can provide.

**Comment by hellocoldworld** [comment]
Hello @pcorpet ! My primary use was for a very very specific function using `codec_options=CodecOptions(document_class=RawBSONDocument)`, bu I desisted (for now). Anyways I looked at your PR and seems like fantastic startign point too extend in the future! Thank you so much for your time.

**Comment by pcorpet** [comment]
This has been implemented in #670.
