### ISSUE TITLE
[Feature Request] add db.getCollectionNames()

### ISSUE THREAD

**Issue by engFelipeMonteiro** [mongomock/mongomock#665]
it can be easly implemented  with:
<pre>
mm = mongomock.MongoClient()['testDatabase']
...
processing
...
collectionNames =  [ x for x in mm._collection_accesses.keys()]
</pre>

**Comment by pcorpet** [comment]
Hi @engFelipeMonteiro , thanks for the bug report.

I believe that `db.getCollectionNames` is using the mongo script syntax. Pymongo is using `db.list_collection_names` which is implemented in `pymongo`.

Feel free to reopen with more details if I got it wrong.
