### ISSUE TITLE
Add support for $map

### ISSUE THREAD

**Issue by lauevrar77** [mongomock/mongomock#677]
Hi,

Would it be possible to add support for $map operation in aggregations ?

I just added this operation to a database query and it breaks around 30 tests in my codebase.

Yours,

Laurent

**Comment by lauevrar77** [comment]
I took a look in the code and I saw that the main problem is the "function definition" in the $map.
However, I think an implementation would be possible if we consider that the function definition is just a "$project" with appropriate parameters. Is that really a potential way to go ?

**Comment by pcorpet** [comment]
For reference you're writing about [$map](https://docs.mongodb.com/manual/reference/operator/aggregation/map/). Yes I believe the implementation should be doable. PRs are welcomed.
