### ISSUE TITLE
Negative limit returns empty

### ISSUE THREAD

**Issue by upcFrost** [mongomock/mongomock#679]
Hi,

I've spotted some issues with negative limits in mongomock, they seem to return an empty batch. According to the doc, they should return the first batch similar to their positive counterparts, but they should close the cursor after that (https://docs.mongodb.com/v4.2/reference/method/cursor.limit/#negative-values)

mongomock from git from https://github.com/mongomock/mongomock/commit/5fe78c7030e1033d1b81964781ec173be92707e9.

**Comment by pcorpet** [comment]
Indeed, that's not OK. We should at least raise a NotImplementedError if we cannot implement the normal pymongo behavior.
