### ISSUE TITLE
mongomock throws error on count operation

### ISSUE THREAD

**Issue by arjunspanicker** [mongomock/mongomock#680]
I have a method where i need to find the count of document in a collection 
i have  a team collection `Class Team` and mocking using mongo mock it throw the error`'Cursor' object has no attribute '_Cursor__spec'` query used is`Team.objects.count()`

**Comment by luca-drf** [comment]
I'm facing the same problem using MongoEngine as described in https://github.com/MongoEngine/mongoengine/issues/2425

**Comment by victorct-pronto** [comment]
Same here, it seems to be that from `mongoengine==0.21.0` the crash appears

**Comment by pcorpet** [comment]
I've pinged the original bug on mongoengine: I believe it's not a feature that mongomock should implement given that `_Cursor__spec` is not part of the public API of `pymongo`

**Comment by pcorpet** [comment]
The original bug MongoEngine/mongoengine#2425 has been fixed another way. Closing this.
