### ISSUE TITLE
Newly added typing stubs not consistent with documentation 

### ISSUE THREAD

**Issue by ee987** [mongomock/mongomock#691]
Typing stubs added recently in https://github.com/mongomock/mongomock/commit/dda5096d9bb68f89a8a47643ba7b8296deed195f is not compatible with documentation from README where servers is a Sequence[Tuple[str,int]]:

Type-annotations:
`def patch(
        servers: Union[str, Sequence[str]] `

README:
`@mongomock.patch(servers=(('server.example.com', 27017),))`

This blocks us from upgrading from 3.21 till 3.22 since we were using the server+port variant of patch which now results in type checking errors.

**Comment by pcorpet** [comment]
Sorry about that. Working on a fix, and some CI checks to make sure we don't have regressions on types.
