### ISSUE TITLE
Faking a connection error

### ISSUE THREAD

**Issue by Seluj78** [mongomock/mongomock#699]
Hi, for some tests I'm writing I'd like to be able to fake an error with my mongodb connection status

Here's the part of code that needs to be tested

```py
mongo_connection_result, mongo_connection_error = self._mongo_client.ping_mongo_connection() 
if mongo_connection_result is not True: 
    response_data['data']['assetService']['status']['overall'] = 'unhealthy' 
    response_data['errors'] = ', '.join([mongo_connection_error]) 
    resp.status = falcon.HTTP_SERVICE_UNAVAILABLE 
```

Does mongomock support faking a connection error ?

**Comment by pcorpet** [comment]
We do not support that at the moment, although I'd love to find an elegant way to provide it. If you have an idea of an interface that you'd like to use, it might help implementing it: how would you declare to `mongomock` that a connection should raise an error?

**Comment by Seluj78** [comment]
Here's how we check if our mongoDB connection currently works (for our `/health` route)

```python
    def ping_mongo_connection(self):
        if self._host == 'mongomock://localhost':
            # 'ismaster' is not implemented in mongomock yet
            return True, None
        result = True
        try:
            self._client.user_data.command('ismaster')
        except Exception as exc:
            self._logger.warning(f'Could not connect to mongo: {exc}')
            return False, f'Mongo Connection Error: {exc}'
        else:
            return result, None
```

As for my tests, I'd like to find a way to have two tests, one that works and one that doesn't.

Maybe there could be a command sent that would work on a real mongoDB client but returns a connection error in mongomock ?
