### ISSUE TITLE
Pylint Travis check fails due to pylint-quotes and recent pylint incompatibility

### ISSUE THREAD

**Issue by m-aciek** [mongomock/mongomock#709]
[Refer here](https://github.com/edaniszewski/pylint-quotes/issues/24) to the origin of the issue. 

We can either wait for
* merge of a fix in pylint-quotes,
* a new pylint release (https://github.com/PyCQA/pylint/issues/4420#issuecomment-828747092) 
* or go with issue poster's suggestion of using pylint's built-in check-quote-consistency.

**Comment by edaniszewski** [comment]
not sure where this sits, but a new version ([0.2.2](https://pypi.org/project/pylint-quotes/0.2.2/)) of pylint-quotes was just released

**Comment by m-aciek** [comment]
Thank you @edaniszewski, it is fixed now: https://travis-ci.org/github/mongomock/mongomock.
