### ISSUE TITLE
Double negation does not work in mongomock e.g. {'$not': {'$not':

### ISSUE THREAD

**Issue by JPBergsma** [mongomock/mongomock#715]
MongoDB correctly handles queries with double negation. Mongomock however returns :
`pymongo.errors.OperationFailure: unknown operator: $not`

This is the filter that failed with mongomock 
{'$and': [{'pretty_formula': {'$not': {'$not': {'$regex': '^Ag2'}}}}, {'pretty_formula': {'$ne': None}}]}

**Comment by pcorpet** [comment]
Fixed by #716
