### ISSUE TITLE
Some Array Expression Operators Are Not Supported

### ISSUE THREAD

**Issue by johngriebel** [mongomock/mongomock#718]
When running my application's unit tests, I get the error `pymongo.errors.OperationFailure: Unrecognized expression '$first'`. When I do something like this:
```
...
{"$project": {"my_field": {"$first": "$some_array_field"}}}
...
```

The error is raised in `aggregate.py` because `"$first"` is not found in the `array_operators` list. It seems a handful of others are missing as well. Is this perhaps intentional, or is this something that could be added? I would be more than happy to create a pull request if need be.

**Comment by pcorpet** [comment]
Yes please, add them at least to raise NotImplemented exception instead of OperationFailure.
