### ISSUE TITLE
Mongoengine GenericReferenceField prevents object from being found.

### ISSUE THREAD

**Issue by quaxsze** [mongomock/mongomock#719]
When using MongoEngine with MongoMock, ReferenceFields work fine, but using GenericReferenceFields return always `None`.
The following snippet reproduces the problem:
```
class User(Document):
    name = StringField()


class Article(Document):
    title = StringField()
    author = GenericReferenceField()


def main():
    connect('mongoenginetest', host='mongomock://localhost')
    user = User(name='John')
    user.save()

    article = Article(title='test', author=user)
    article.save()

    fresh_art = Article.objects(author=user.id).first()
    assert fresh_art.title == 'test'
```

When replacing the `GenericReferenceField()` by `ReferenceField('User')`, the article is found.

**Comment by pcorpet** [comment]
Thanks for the report. Unfortunately, I'm not familiar enough with MongoEngine so it's hard for me to understand the issue. Maybe if you can refine a bit more by looking at MongoEngine's code and how it calls mongomock's API, it would be easier to investigate?

**Comment by quaxsze** [comment]
Hello,

The query made by the line `Article.objects(author=user.id).first()` is `{'author._ref.$id': ObjectId('61371dd73b32f1c00489f00e')}`
The `_ref` part seems to be the problem.

**Comment by pcorpet** [comment]
OK, this seems due to #759 as well.
