### ISSUE TITLE
bson.errors.invalidDocument: key * must not contains '.'

### ISSUE THREAD

**Issue by engFelipeMonteiro** [mongomock/mongomock#720]
When using a real mongodb database I can include a entry like a below, but in mongomock it not possible.

{"object.name": value} 

When I add this in real database it works, but in mongomock doesn`t.

**Comment by oekstein** [comment]
Just encountered the same problem..  Any update on this issue?

**Comment by pcorpet** [comment]
Thanks for reporting this. Handling key with dots is not supported by `mongomock` yet. PRs are welcomed though.
