### ISSUE TITLE
list_collection_names should support kwargs

### ISSUE THREAD

**Issue by sschiessl-bcp** [mongomock/mongomock#736]
The function `list_collection_names` supports kwargs https://github.com/mongodb/mongo-python-driver/blob/master/pymongo/database.py#L683 and should also do so in mongomock, otherwise a call like this will fail

```
mongomock.MongoClient()["some_name"].list_collection_names(
    include_system_collections=False
)
```

**Comment by pcorpet** [comment]
Actually this is a bad example as such a command would also fail using pymongo with a:
```sh
pymongo.errors.OperationFailure: BSON field 'listCollections.include_system_collections' is an unknown field., full error: {'ok': 0.0, 'errmsg': "BSON field 'listCollections.include_system_collections' is
 an unknown field.", 'code': 40415, 'codeName': 'Location40415'}
```

I don't think there's a strong benefit in getting the right error type: your code should avoid those calls. Please reopen if I've missed something.

**Comment by sschiessl-bcp** [comment]
I have the code in my post above running in production wihtout error. Can you please present an example when it fails?
