### ISSUE TITLE
enable_gridfs_integration broken for Python 3.10

### ISSUE THREAD

**Issue by thequilo** [mongomock/mongomock#758]
Python 3.10 changed the way builtins are found at execution time (https://docs.python.org/3/whatsnew/3.10.html):

> Functions have a new __builtins__ attribute which is used to look for builtin symbols when a function is executed, instead of looking into __globals__['__builtins__']. The attribute is initialized from __globals__["__builtins__"] if it exists, else from the current builtins. (Contributed by Mark Shannon in [bpo-42990](https://bugs.python.org/issue42990).)

So, now the `isinstance` check in `GridFS.__init__` is not patched correctly. Example (only fails for Python 3.10):

```python
import mongomock
from mongomock.gridfs import enable_gridfs_integration
import gridfs

enable_gridfs_integration()
db = mongomock.MongoClient().db
fs = gridfs.GridFS(db)
```
raises:

```
Traceback (most recent call last):
  ...
  File ".../python3.10/site-packages/gridfs/__init__.py", line 74, in __init__
    raise TypeError("database must be an instance of Database")
TypeError: database must be an instance of Database
```

**Comment by pcorpet** [comment]
Thanks a lot! I was investigating that yesterday, and couldn't pinpoint the exact change.

**Comment by pcorpet** [comment]
Would you mind reviewing #761 @thequilo please?

**Comment by thequilo** [comment]
Thank you!

**Comment by thequilo** [comment]
Do you have any idea how long it is going to take until this fix is on PyPi?
