### ISSUE TITLE
Read Preference error 

### ISSUE THREAD

**Issue by eniolakunle** [mongomock/mongomock#760]
Hi, 

Trying to upgrade my teams version of pymongo to 2.9.5, and running into this error within our tests, and its coming from mongo mock? 

Any ideas whats happening? Can't find much online.

```
`self = Collection(Database(mongomock.MongoClient('localhost', 27017), 'db'), 'blah')

codec_options = CodecOptions(document_class=<class 'dict'>, tz_aware=False, uuid_representation=3, unicode_decode_error_handler='strict', tzinfo=None)

read_preference = 0, write_concern = None, read_concern = None



    def with_options(

            self, codec_options=None, read_preference=None, write_concern=None, read_concern=None):

        has_changes = False

        for key, options in iteritems(_WITH_OPTIONS_KWARGS):

            value = locals()[key]

            if value is None or value == getattr(self, '_' + key):

                continue

            has_changes = True

            for attr in options.attrs:

                if not hasattr(value, attr):

                    raise TypeError(

>                       '{} must be an instance of {}'.format(key, options.typename))

E                   TypeError: read_preference must be an instance of pymongo.read_preference.ReadPreference`
```

**Comment by pcorpet** [comment]
We do not support `pymongo` v2.9.5. I think this is because we check for some properties of ReadPreference class that was added later. Is it possible for you to update to a more recent version of pymongo? or use an older version of monogmock?

**Comment by eniolakunle** [comment]
> We do not support `pymongo` v2.9.5. I think this is because we check for some properties of ReadPreference class that was added later. Is it possible for you to update to a more recent version of pymongo? or use an older version of monogmock?

Thanks for the response! We can't upgrade past 3 at moment, but I will try an older version of mongomock and see. We are using 3.19.0 currently.

**Comment by eniolakunle** [comment]
Using mongo mock 3.7.0 seems to have gotten me past this error. Thanks!
