### ISSUE TITLE
Will there be a new release soon?

### ISSUE THREAD

**Issue by scottbelden** [mongomock/mongomock#785]
I think I'm running into this issue which looks like it has been fixed but not released: https://github.com/mongomock/mongomock/issues/758

Are there plans to create a new release soon?

**Comment by pcorpet** [comment]
Yes, I'd like to release one before next week. I want to close some of the open pull requests that don't require a lot of work before. Please ping me again next week if nothing happens, I'll do a partial release then.

**Comment by scottbelden** [comment]
Thanks! I'll try to remember to ping if it is needed.

**Comment by TheBatmanofButler** [comment]
Hi, I love your library! I just wanted to mention that I am also running into an issue that is fixed but not yet released: https://github.com/mongomock/mongomock/pull/695

Looking forward to the next release.

**Comment by pcorpet** [comment]
Here you go, https://github.com/mongomock/mongomock/releases/tag/4.1.2

**Comment by scottbelden** [comment]
Thanks!
