### ISSUE TITLE
pkg_resources is deprecated as an API

### ISSUE THREAD

**Issue by durgeksh** [mongomock/mongomock#848]
When I import the library, I am getting error as below:

venv/lib/python3.10/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
    warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html

I am running the tests as pytest -vv

**Comment by mdomke** [comment]
Since #834 has been merged we can close this issue. I t will be part of the next release.

**Comment by paul-leydier** [comment]
Hi! When do you think the next release will be live? This might be an issue for projects migrating to python 3.12
Thanks for your work on this!
