### ISSUE TITLE
What tox version should be used?

### ISSUE THREAD

**Issue by martincpt** [mongomock/mongomock#883]
`tox.ini` format seems to be incompatible with latest version of tox. I receive the following errors with tox==4.14.1:

    failed with pass_env values cannot contain whitespace, use comma to have multiple values in a single line, invalid values found 'CI TRAVIS TRAVIS_* TEST_MONGO_HOST MONGODB'

What tox version should be used to run this package?

**Comment by mdomke** [comment]
The project hast switched to [hatch](https://hatch.pypa.io/latest/) for virtual environment management. Please refer to the installation instructions in the `README.rst`. You can then run 
```console
$ hatch test
```
