### ISSUE TITLE
4.1.3 is not published

### ISSUE THREAD

**Issue by fatelei** [mongomock/mongomock#889]
<img width="1004" alt="image" src="https://github.com/mongomock/mongomock/assets/961094/eea7e12a-f267-4fe7-ad2e-eb430c1d1074">

**Comment by JeremyKulchyk** [comment]
Please release

**Comment by ml-evs** [comment]
Would really appreciate this too, given that I fixed this in a PR #834 18 months ago

**Comment by mdomke** [comment]
I released `4.2.0.post1` instead 😉
